-- Auto-generated by the following command:
-- $ nvim --headless "+luafile generate_filetypes.lua" +q

---@type ContextGroup
return {
  title = "Filetypes",
  entries = {
    ada = {
      label = "ada",
      filetype = "ada",
      commands = {
        rg = { flags = { "--type", "ada" } },
        git_grep = {
          globs = {
            "*.adb",
            "*.ads",
          },
        },
      },
    },
    amake = {
      label = "amake",
      icon = { "", "DevIconMakefile" },
      commands = {
        rg = { flags = { "--type", "amake" } },
        git_grep = {
          globs = {
            "*.bp",
            "*.mk",
          },
        },
      },
    },
    asciidoc = {
      label = "asciidoc",
      icon = { "󰦝", "DevIconAsc" },
      commands = {
        rg = { flags = { "--type", "asciidoc" } },
        git_grep = {
          globs = {
            "*.adoc",
            "*.asc",
            "*.asciidoc",
          },
        },
      },
    },
    asm = {
      label = "asm",
      filetype = "asm",
      commands = {
        rg = { flags = { "--type", "asm" } },
        git_grep = {
          globs = {
            "*.S",
            "*.asm",
            "*.s",
          },
        },
      },
    },
    awk = {
      label = "awk",
      filetype = "awk",
      commands = {
        rg = { flags = { "--type", "awk" } },
        git_grep = { globs = { "*.awk" } },
      },
    },
    bat = {
      label = "bat",
      icon = { "", "DevIconBat" },
      commands = {
        rg = { flags = { "--type", "bat" } },
        git_grep = { globs = { "*.bat" } },
      },
    },
    batch = {
      label = "batch",
      icon = { "", "DevIconBat" },
      commands = {
        rg = { flags = { "--type", "batch" } },
        git_grep = { globs = { "*.bat" } },
      },
    },
    bazel = {
      label = "bazel",
      icon = { "", "DevIconBazel" },
      commands = {
        rg = { flags = { "--type", "bazel" } },
        git_grep = {
          globs = {
            "*.BUILD",
            "*.bazel",
            "*.bazelrc",
            "*.bzl",
            "BUILD",
            "MODULE.bazel",
            "WORKSPACE",
            "WORKSPACE.bazel",
          },
        },
      },
    },
    bitbake = {
      label = "bitbake",
      icon = { "", "DevIconConf" },
      commands = {
        rg = { flags = { "--type", "bitbake" } },
        git_grep = {
          globs = {
            "*.bb",
            "*.bbappend",
            "*.bbclass",
            "*.conf",
            "*.inc",
          },
        },
      },
    },
    bzip2 = {
      label = "bzip2",
      icon = { "", "DevIconBz2" },
      commands = {
        rg = { flags = { "--type", "bzip2" } },
        git_grep = {
          globs = {
            "*.bz2",
            "*.tbz2",
          },
        },
      },
    },
    clojure = {
      label = "clojure",
      filetype = "clojure",
      commands = {
        rg = { flags = { "--type", "clojure" } },
        git_grep = {
          globs = {
            "*.clj",
            "*.cljc",
            "*.cljs",
            "*.cljx",
          },
        },
      },
    },
    cmake = {
      label = "cmake",
      filetype = "cmake",
      commands = {
        rg = { flags = { "--type", "cmake" } },
        git_grep = {
          globs = {
            "*.cmake",
            "CMakeLists.txt",
          },
        },
      },
    },
    cmd = {
      label = "cmd",
      icon = { "", "DevIconBat" },
      commands = {
        rg = { flags = { "--type", "cmd" } },
        git_grep = {
          globs = {
            "*.bat",
            "*.cmd",
          },
        },
      },
    },
    coffeescript = {
      label = "coffeescript",
      icon = { "", "DevIconCoffee" },
      commands = {
        rg = { flags = { "--type", "coffeescript" } },
        git_grep = { globs = { "*.coffee" } },
      },
    },
    config = {
      label = "config",
      icon = { "", "DevIconConfiguration" },
      commands = {
        rg = { flags = { "--type", "config" } },
        git_grep = {
          globs = {
            "*.cfg",
            "*.conf",
            "*.config",
            "*.ini",
          },
        },
      },
    },
    coq = {
      label = "coq",
      icon = { "󰍛", "DevIconVerilog" },
      commands = {
        rg = { flags = { "--type", "coq" } },
        git_grep = { globs = { "*.v" } },
      },
    },
    cpp = {
      label = "cpp",
      filetype = "cpp",
      commands = {
        rg = { flags = { "--type", "cpp" } },
        git_grep = {
          globs = {
            "*.[ChH]",
            "*.[ChH].in",
            "*.[ch]pp",
            "*.[ch]pp.in",
            "*.[ch]xx",
            "*.[ch]xx.in",
            "*.cc",
            "*.cc.in",
            "*.hh",
            "*.hh.in",
            "*.inl",
          },
        },
      },
    },
    crystal = {
      label = "crystal",
      icon = { "", "DevIconCrystal" },
      commands = {
        rg = { flags = { "--type", "crystal" } },
        git_grep = {
          globs = {
            "*.cr",
            "*.ecr",
            "Projectfile",
            "shard.yml",
          },
        },
      },
    },
    cs = {
      label = "cs",
      filetype = "cs",
      commands = {
        rg = { flags = { "--type", "cs" } },
        git_grep = { globs = { "*.cs" } },
      },
    },
    csharp = {
      label = "csharp",
      icon = { "󰌛", "DevIconCs" },
      commands = {
        rg = { flags = { "--type", "csharp" } },
        git_grep = { globs = { "*.cs" } },
      },
    },
    cshtml = {
      label = "cshtml",
      icon = { "󱦗", "DevIconRazorPage" },
      commands = {
        rg = { flags = { "--type", "cshtml" } },
        git_grep = { globs = { "*.cshtml" } },
      },
    },
    csproj = {
      label = "csproj",
      icon = { "󰪮", "DevIconCSharpProject" },
      commands = {
        rg = { flags = { "--type", "csproj" } },
        git_grep = { globs = { "*.csproj" } },
      },
    },
    css = {
      label = "css",
      filetype = "css",
      commands = {
        rg = { flags = { "--type", "css" } },
        git_grep = {
          globs = {
            "*.css",
            "*.scss",
          },
        },
      },
    },
    csv = {
      label = "csv",
      filetype = "csv",
      commands = {
        rg = { flags = { "--type", "csv" } },
        git_grep = { globs = { "*.csv" } },
      },
    },
    cuda = {
      label = "cuda",
      filetype = "cuda",
      commands = {
        rg = { flags = { "--type", "cuda" } },
        git_grep = {
          globs = {
            "*.cu",
            "*.cuh",
          },
        },
      },
    },
    cython = {
      label = "cython",
      icon = { "", "DevIconPxd" },
      commands = {
        rg = { flags = { "--type", "cython" } },
        git_grep = {
          globs = {
            "*.pxd",
            "*.pxi",
            "*.pyx",
          },
        },
      },
    },
    d = {
      label = "d",
      filetype = "d",
      commands = {
        rg = { flags = { "--type", "d" } },
        git_grep = { globs = { "*.d" } },
      },
    },
    dart = {
      label = "dart",
      filetype = "dart",
      commands = {
        rg = { flags = { "--type", "dart" } },
        git_grep = { globs = { "*.dart" } },
      },
    },
    diff = {
      label = "diff",
      filetype = "diff",
      commands = {
        rg = { flags = { "--type", "diff" } },
        git_grep = {
          globs = {
            "*.diff",
            "*.patch",
          },
        },
      },
    },
    dockercompose = {
      label = "dockercompose",
      icon = { "", "DevIconYml" },
      commands = {
        rg = { flags = { "--type", "dockercompose" } },
        git_grep = {
          globs = {
            "docker-compose.*.yml",
            "docker-compose.yml",
          },
        },
      },
    },
    ebuild = {
      label = "ebuild",
      icon = { "", "DevIconGentooBuild" },
      commands = {
        rg = { flags = { "--type", "ebuild" } },
        git_grep = {
          globs = {
            "*.ebuild",
            "*.eclass",
          },
        },
      },
    },
    edn = {
      label = "edn",
      icon = { "", "DevIconEdn" },
      commands = {
        rg = { flags = { "--type", "edn" } },
        git_grep = { globs = { "*.edn" } },
      },
    },
    elisp = {
      label = "elisp",
      icon = { "", "DevIconElisp" },
      commands = {
        rg = { flags = { "--type", "elisp" } },
        git_grep = { globs = { "*.el" } },
      },
    },
    elixir = {
      label = "elixir",
      filetype = "elixir",
      commands = {
        rg = { flags = { "--type", "elixir" } },
        git_grep = {
          globs = {
            "*.eex",
            "*.ex",
            "*.exs",
            "*.heex",
            "*.leex",
            "*.livemd",
          },
        },
      },
    },
    elm = {
      label = "elm",
      filetype = "elm",
      commands = {
        rg = { flags = { "--type", "elm" } },
        git_grep = { globs = { "*.elm" } },
      },
    },
    erb = {
      label = "erb",
      icon = { "", "DevIconErb" },
      commands = {
        rg = { flags = { "--type", "erb" } },
        git_grep = { globs = { "*.erb" } },
      },
    },
    erlang = {
      label = "erlang",
      filetype = "erlang",
      commands = {
        rg = { flags = { "--type", "erlang" } },
        git_grep = {
          globs = {
            "*.erl",
            "*.hrl",
          },
        },
      },
    },
    fennel = {
      label = "fennel",
      filetype = "fennel",
      commands = {
        rg = { flags = { "--type", "fennel" } },
        git_grep = { globs = { "*.fnl" } },
      },
    },
    fish = {
      label = "fish",
      filetype = "fish",
      commands = {
        rg = { flags = { "--type", "fish" } },
        git_grep = { globs = { "*.fish" } },
      },
    },
    fortran = {
      label = "fortran",
      filetype = "fortran",
      commands = {
        rg = { flags = { "--type", "fortran" } },
        git_grep = {
          globs = {
            "*.F",
            "*.F77",
            "*.F90",
            "*.F95",
            "*.f",
            "*.f77",
            "*.f90",
            "*.f95",
            "*.pfo",
          },
        },
      },
    },
    fsharp = {
      label = "fsharp",
      filetype = "fsharp",
      commands = {
        rg = { flags = { "--type", "fsharp" } },
        git_grep = {
          globs = {
            "*.fs",
            "*.fsi",
            "*.fsx",
          },
        },
      },
    },
    gap = {
      label = "gap",
      icon = { "", "DevIconGDScript" },
      commands = {
        rg = { flags = { "--type", "gap" } },
        git_grep = {
          globs = {
            "*.g",
            "*.gap",
            "*.gd",
            "*.gi",
            "*.tst",
          },
        },
      },
    },
    go = {
      label = "go",
      filetype = "go",
      commands = {
        rg = { flags = { "--type", "go" } },
        git_grep = { globs = { "*.go" } },
      },
    },
    gprbuild = {
      label = "gprbuild",
      icon = { "", "DevIconGPRBuildProject" },
      commands = {
        rg = { flags = { "--type", "gprbuild" } },
        git_grep = { globs = { "*.gpr" } },
      },
    },
    gradle = {
      label = "gradle",
      icon = { "", "DevIconGradle" },
      commands = {
        rg = { flags = { "--type", "gradle" } },
        git_grep = {
          globs = {
            "*.gradle",
            "*.gradle.kts",
            "gradle-wrapper.*",
            "gradle.properties",
            "gradlew",
            "gradlew.bat",
          },
        },
      },
    },
    graphql = {
      label = "graphql",
      filetype = "graphql",
      commands = {
        rg = { flags = { "--type", "graphql" } },
        git_grep = {
          globs = {
            "*.graphql",
            "*.graphqls",
          },
        },
      },
    },
    groovy = {
      label = "groovy",
      filetype = "groovy",
      commands = {
        rg = { flags = { "--type", "groovy" } },
        git_grep = {
          globs = {
            "*.gradle",
            "*.groovy",
          },
        },
      },
    },
    gzip = {
      label = "gzip",
      icon = { "", "DevIconGz" },
      commands = {
        rg = { flags = { "--type", "gzip" } },
        git_grep = {
          globs = {
            "*.gz",
            "*.tgz",
          },
        },
      },
    },
    h = {
      label = "h",
      icon = { "", "DevIconH" },
      commands = {
        rg = { flags = { "--type", "h" } },
        git_grep = {
          globs = {
            "*.h",
            "*.hh",
            "*.hpp",
          },
        },
      },
    },
    haml = {
      label = "haml",
      filetype = "haml",
      commands = {
        rg = { flags = { "--type", "haml" } },
        git_grep = { globs = { "*.haml" } },
      },
    },
    haskell = {
      label = "haskell",
      filetype = "haskell",
      commands = {
        rg = { flags = { "--type", "haskell" } },
        git_grep = {
          globs = {
            "*.c2hs",
            "*.cpphs",
            "*.hs",
            "*.hsc",
            "*.lhs",
          },
        },
      },
    },
    hbs = {
      label = "hbs",
      filetype = "hbs",
      commands = {
        rg = { flags = { "--type", "hbs" } },
        git_grep = { globs = { "*.hbs" } },
      },
    },
    hs = {
      label = "hs",
      icon = { "", "DevIconHs" },
      commands = {
        rg = { flags = { "--type", "hs" } },
        git_grep = {
          globs = {
            "*.hs",
            "*.lhs",
          },
        },
      },
    },
    html = {
      label = "html",
      filetype = "html",
      commands = {
        rg = { flags = { "--type", "html" } },
        git_grep = {
          globs = {
            "*.ejs",
            "*.htm",
            "*.html",
          },
        },
      },
    },
    java = {
      label = "java",
      filetype = "java",
      commands = {
        rg = { flags = { "--type", "java" } },
        git_grep = {
          globs = {
            "*.java",
            "*.jsp",
            "*.jspx",
            "*.properties",
          },
        },
      },
    },
    jl = {
      label = "jl",
      icon = { "", "DevIconJl" },
      commands = {
        rg = { flags = { "--type", "jl" } },
        git_grep = { globs = { "*.jl" } },
      },
    },
    js = {
      label = "js",
      icon = { "", "DevIconCjs" },
      commands = {
        rg = { flags = { "--type", "js" } },
        git_grep = {
          globs = {
            "*.cjs",
            "*.js",
            "*.jsx",
            "*.mjs",
            "*.vue",
          },
        },
      },
    },
    json = {
      label = "json",
      filetype = "json",
      commands = {
        rg = { flags = { "--type", "json" } },
        git_grep = {
          globs = {
            "*.json",
            "*.sarif",
            "composer.lock",
          },
        },
      },
    },
    julia = {
      label = "julia",
      filetype = "julia",
      commands = {
        rg = { flags = { "--type", "julia" } },
        git_grep = { globs = { "*.jl" } },
      },
    },
    jupyter = {
      label = "jupyter",
      icon = { "", "DevIconNotebook" },
      commands = {
        rg = { flags = { "--type", "jupyter" } },
        git_grep = {
          globs = {
            "*.ipynb",
            "*.jpynb",
          },
        },
      },
    },
    kotlin = {
      label = "kotlin",
      filetype = "kotlin",
      commands = {
        rg = { flags = { "--type", "kotlin" } },
        git_grep = {
          globs = {
            "*.kt",
            "*.kts",
          },
        },
      },
    },
    less = {
      label = "less",
      filetype = "less",
      commands = {
        rg = { flags = { "--type", "less" } },
        git_grep = { globs = { "*.less" } },
      },
    },
    lisp = {
      label = "lisp",
      icon = { "", "DevIconElisp" },
      commands = {
        rg = { flags = { "--type", "lisp" } },
        git_grep = {
          globs = {
            "*.el",
            "*.jl",
            "*.lisp",
            "*.lsp",
            "*.sc",
            "*.scm",
          },
        },
      },
    },
    lock = {
      label = "lock",
      filetype = "lock",
      commands = {
        rg = { flags = { "--type", "lock" } },
        git_grep = {
          globs = {
            "*.lock",
            "package-lock.json",
          },
        },
      },
    },
    log = {
      label = "log",
      filetype = "log",
      commands = {
        rg = { flags = { "--type", "log" } },
        git_grep = { globs = { "*.log" } },
      },
    },
    lua = {
      label = "lua",
      filetype = "lua",
      commands = {
        rg = { flags = { "--type", "lua" } },
        git_grep = { globs = { "*.lua" } },
      },
    },
    make = {
      label = "make",
      filetype = "make",
      commands = {
        rg = { flags = { "--type", "make" } },
        git_grep = {
          globs = {
            "*.mak",
            "*.mk",
            "[Gg][Nn][Uu]makefile",
            "[Gg][Nn][Uu]makefile.am",
            "[Gg][Nn][Uu]makefile.in",
            "[Mm]akefile",
            "[Mm]akefile.am",
            "[Mm]akefile.in",
          },
        },
      },
    },
    markdown = {
      label = "markdown",
      filetype = "markdown",
      commands = {
        rg = { flags = { "--type", "markdown" } },
        git_grep = {
          globs = {
            "*.markdown",
            "*.md",
            "*.mdown",
            "*.mdwn",
            "*.mdx",
            "*.mkd",
            "*.mkdn",
          },
        },
      },
    },
    matlab = {
      label = "matlab",
      icon = { "", "DevIconObjectiveC" },
      commands = {
        rg = { flags = { "--type", "matlab" } },
        git_grep = { globs = { "*.m" } },
      },
    },
    md = {
      label = "md",
      icon = { "", "DevIconMarkdown" },
      commands = {
        rg = { flags = { "--type", "md" } },
        git_grep = {
          globs = {
            "*.markdown",
            "*.md",
            "*.mdown",
            "*.mdwn",
            "*.mdx",
            "*.mkd",
            "*.mkdn",
          },
        },
      },
    },
    mint = {
      label = "mint",
      filetype = "mint",
      commands = {
        rg = { flags = { "--type", "mint" } },
        git_grep = { globs = { "*.mint" } },
      },
    },
    ml = {
      label = "ml",
      icon = { "", "DevIconMl" },
      commands = {
        rg = { flags = { "--type", "ml" } },
        git_grep = { globs = { "*.ml" } },
      },
    },
    motoko = {
      label = "motoko",
      filetype = "motoko",
      commands = {
        rg = { flags = { "--type", "motoko" } },
        git_grep = { globs = { "*.mo" } },
      },
    },
    msbuild = {
      label = "msbuild",
      icon = { "󰪮", "DevIconCSharpProject" },
      commands = {
        rg = { flags = { "--type", "msbuild" } },
        git_grep = {
          globs = {
            "*.csproj",
            "*.fsproj",
            "*.proj",
            "*.props",
            "*.sln",
            "*.targets",
            "*.vcxproj",
          },
        },
      },
    },
    nim = {
      label = "nim",
      filetype = "nim",
      commands = {
        rg = { flags = { "--type", "nim" } },
        git_grep = {
          globs = {
            "*.nim",
            "*.nimble",
            "*.nimf",
            "*.nims",
          },
        },
      },
    },
    nix = {
      label = "nix",
      filetype = "nix",
      commands = {
        rg = { flags = { "--type", "nix" } },
        git_grep = { globs = { "*.nix" } },
      },
    },
    objc = {
      label = "objc",
      icon = { "", "DevIconH" },
      commands = {
        rg = { flags = { "--type", "objc" } },
        git_grep = {
          globs = {
            "*.h",
            "*.m",
          },
        },
      },
    },
    objcpp = {
      label = "objcpp",
      icon = { "", "DevIconH" },
      commands = {
        rg = { flags = { "--type", "objcpp" } },
        git_grep = {
          globs = {
            "*.h",
            "*.mm",
          },
        },
      },
    },
    ocaml = {
      label = "ocaml",
      filetype = "ocaml",
      commands = {
        rg = { flags = { "--type", "ocaml" } },
        git_grep = {
          globs = {
            "*.ml",
            "*.mli",
            "*.mll",
            "*.mly",
          },
        },
      },
    },
    org = {
      label = "org",
      filetype = "org",
      commands = {
        rg = { flags = { "--type", "org" } },
        git_grep = {
          globs = {
            "*.org",
            "*.org_archive",
          },
        },
      },
    },
    pascal = {
      label = "pascal",
      icon = { "", "DevIconPp" },
      commands = {
        rg = { flags = { "--type", "pascal" } },
        git_grep = {
          globs = {
            "*.dpr",
            "*.inc",
            "*.lpr",
            "*.pas",
            "*.pp",
          },
        },
      },
    },
    pdf = {
      label = "pdf",
      filetype = "pdf",
      commands = {
        rg = { flags = { "--type", "pdf" } },
        git_grep = { globs = { "*.pdf" } },
      },
    },
    perl = {
      label = "perl",
      filetype = "perl",
      commands = {
        rg = { flags = { "--type", "perl" } },
        git_grep = {
          globs = {
            "*.PL",
            "*.perl",
            "*.pl",
            "*.plh",
            "*.plx",
            "*.pm",
            "*.t",
          },
        },
      },
    },
    php = {
      label = "php",
      filetype = "php",
      commands = {
        rg = { flags = { "--type", "php" } },
        git_grep = {
          globs = {
            "*.php",
            "*.php3",
            "*.php4",
            "*.php5",
            "*.php7",
            "*.php8",
            "*.pht",
            "*.phtml",
          },
        },
      },
    },
    po = {
      label = "po",
      filetype = "po",
      commands = {
        rg = { flags = { "--type", "po" } },
        git_grep = { globs = { "*.po" } },
      },
    },
    prolog = {
      label = "prolog",
      filetype = "prolog",
      commands = {
        rg = { flags = { "--type", "prolog" } },
        git_grep = {
          globs = {
            "*.P",
            "*.pl",
            "*.pro",
            "*.prolog",
          },
        },
      },
    },
    ps = {
      label = "ps",
      icon = { "󰨊", "DevIconPsScriptfile" },
      commands = {
        rg = { flags = { "--type", "ps" } },
        git_grep = {
          globs = {
            "*.cdxml",
            "*.ps1",
            "*.ps1xml",
            "*.psd1",
            "*.psm1",
          },
        },
      },
    },
    puppet = {
      label = "puppet",
      filetype = "puppet",
      commands = {
        rg = { flags = { "--type", "puppet" } },
        git_grep = {
          globs = {
            "*.epp",
            "*.erb",
            "*.pp",
            "*.rb",
          },
        },
      },
    },
    py = {
      label = "py",
      icon = { "", "DevIconPy" },
      commands = {
        rg = { flags = { "--type", "py" } },
        git_grep = {
          globs = {
            "*.py",
            "*.pyi",
          },
        },
      },
    },
    python = {
      label = "python",
      filetype = "python",
      commands = {
        rg = { flags = { "--type", "python" } },
        git_grep = {
          globs = {
            "*.py",
            "*.pyi",
          },
        },
      },
    },
    qmake = {
      label = "qmake",
      icon = { "", "DevIconProlog" },
      commands = {
        rg = { flags = { "--type", "qmake" } },
        git_grep = {
          globs = {
            "*.prf",
            "*.pri",
            "*.pro",
          },
        },
      },
    },
    qml = {
      label = "qml",
      filetype = "qml",
      commands = {
        rg = { flags = { "--type", "qml" } },
        git_grep = { globs = { "*.qml" } },
      },
    },
    r = {
      label = "r",
      filetype = "r",
      commands = {
        rg = { flags = { "--type", "r" } },
        git_grep = {
          globs = {
            "*.R",
            "*.Rmd",
            "*.Rnw",
            "*.r",
          },
        },
      },
    },
    red = {
      label = "red",
      icon = { "󰟔", "DevIconR" },
      commands = {
        rg = { flags = { "--type", "red" } },
        git_grep = {
          globs = {
            "*.r",
            "*.red",
            "*.reds",
          },
        },
      },
    },
    rescript = {
      label = "rescript",
      icon = { "", "DevIconReScript" },
      commands = {
        rg = { flags = { "--type", "rescript" } },
        git_grep = {
          globs = {
            "*.res",
            "*.resi",
          },
        },
      },
    },
    ruby = {
      label = "ruby",
      filetype = "ruby",
      commands = {
        rg = { flags = { "--type", "ruby" } },
        git_grep = {
          globs = {
            "*.gemspec",
            "*.rb",
            "*.rbw",
            ".irbrc",
            "Gemfile",
            "Rakefile",
            "config.ru",
          },
        },
      },
    },
    rust = {
      label = "rust",
      filetype = "rust",
      commands = {
        rg = { flags = { "--type", "rust" } },
        git_grep = { globs = { "*.rs" } },
      },
    },
    sass = {
      label = "sass",
      filetype = "sass",
      commands = {
        rg = { flags = { "--type", "sass" } },
        git_grep = {
          globs = {
            "*.sass",
            "*.scss",
          },
        },
      },
    },
    scala = {
      label = "scala",
      filetype = "scala",
      commands = {
        rg = { flags = { "--type", "scala" } },
        git_grep = {
          globs = {
            "*.sbt",
            "*.scala",
          },
        },
      },
    },
    sh = {
      label = "sh",
      filetype = "sh",
      commands = {
        rg = { flags = { "--type", "sh" } },
        git_grep = {
          globs = {
            "*.bash",
            "*.bashrc",
            "*.csh",
            "*.cshrc",
            "*.ksh",
            "*.kshrc",
            "*.sh",
            "*.tcsh",
            "*.zsh",
            ".bash_login",
            ".bash_logout",
            ".bash_profile",
            ".bashrc",
            ".cshrc",
            ".kshrc",
            ".login",
            ".logout",
            ".profile",
            ".tcshrc",
            ".zlogin",
            ".zlogout",
            ".zprofile",
            ".zshenv",
            ".zshrc",
            "bash_login",
            "bash_logout",
            "bash_profile",
            "bashrc",
            "profile",
            "zlogin",
            "zlogout",
            "zprofile",
            "zshenv",
            "zshrc",
          },
        },
      },
    },
    slim = {
      label = "slim",
      filetype = "slim",
      commands = {
        rg = { flags = { "--type", "slim" } },
        git_grep = {
          globs = {
            "*.skim",
            "*.slim",
            "*.slime",
          },
        },
      },
    },
    sml = {
      label = "sml",
      filetype = "sml",
      commands = {
        rg = { flags = { "--type", "sml" } },
        git_grep = {
          globs = {
            "*.sig",
            "*.sml",
          },
        },
      },
    },
    solidity = {
      label = "solidity",
      filetype = "solidity",
      commands = {
        rg = { flags = { "--type", "solidity" } },
        git_grep = { globs = { "*.sol" } },
      },
    },
    sql = {
      label = "sql",
      filetype = "sql",
      commands = {
        rg = { flags = { "--type", "sql" } },
        git_grep = {
          globs = {
            "*.psql",
            "*.sql",
          },
        },
      },
    },
    stylus = {
      label = "stylus",
      icon = { "", "DevIconStyl" },
      commands = {
        rg = { flags = { "--type", "stylus" } },
        git_grep = { globs = { "*.styl" } },
      },
    },
    sv = {
      label = "sv",
      icon = { "", "DevIconH" },
      commands = {
        rg = { flags = { "--type", "sv" } },
        git_grep = {
          globs = {
            "*.h",
            "*.sv",
            "*.svh",
            "*.v",
            "*.vg",
          },
        },
      },
    },
    svelte = {
      label = "svelte",
      filetype = "svelte",
      commands = {
        rg = { flags = { "--type", "svelte" } },
        git_grep = { globs = { "*.svelte" } },
      },
    },
    svg = {
      label = "svg",
      filetype = "svg",
      commands = {
        rg = { flags = { "--type", "svg" } },
        git_grep = { globs = { "*.svg" } },
      },
    },
    swift = {
      label = "swift",
      filetype = "swift",
      commands = {
        rg = { flags = { "--type", "swift" } },
        git_grep = { globs = { "*.swift" } },
      },
    },
    systemd = {
      label = "systemd",
      icon = { "", "DevIconConf" },
      commands = {
        rg = { flags = { "--type", "systemd" } },
        git_grep = {
          globs = {
            "*.automount",
            "*.conf",
            "*.device",
            "*.link",
            "*.mount",
            "*.path",
            "*.scope",
            "*.service",
            "*.slice",
            "*.socket",
            "*.swap",
            "*.target",
            "*.timer",
          },
        },
      },
    },
    tcl = {
      label = "tcl",
      filetype = "tcl",
      commands = {
        rg = { flags = { "--type", "tcl" } },
        git_grep = { globs = { "*.tcl" } },
      },
    },
    tex = {
      label = "tex",
      filetype = "tex",
      commands = {
        rg = { flags = { "--type", "tex" } },
        git_grep = {
          globs = {
            "*.bib",
            "*.cls",
            "*.dtx",
            "*.ins",
            "*.ltx",
            "*.sty",
            "*.tex",
          },
        },
      },
    },
    tf = {
      label = "tf",
      filetype = "tf",
      commands = {
        rg = { flags = { "--type", "tf" } },
        git_grep = {
          globs = {
            "*.auto.tfvars",
            "*.auto.tfvars.json",
            "*.terraform.lock.hcl",
            "*.terraformrc",
            "*.tf",
            "*.tf.json",
            "*.tfrc",
            "terraform.rc",
            "terraform.tfvars",
            "terraform.tfvars.json",
          },
        },
      },
    },
    toml = {
      label = "toml",
      filetype = "toml",
      commands = {
        rg = { flags = { "--type", "toml" } },
        git_grep = {
          globs = {
            "*.toml",
            "Cargo.lock",
          },
        },
      },
    },
    ts = {
      label = "ts",
      icon = { "", "DevIconCts" },
      commands = {
        rg = { flags = { "--type", "ts" } },
        git_grep = {
          globs = {
            "*.cts",
            "*.mts",
            "*.ts",
            "*.tsx",
          },
        },
      },
    },
    twig = {
      label = "twig",
      filetype = "twig",
      commands = {
        rg = { flags = { "--type", "twig" } },
        git_grep = { globs = { "*.twig" } },
      },
    },
    txt = {
      label = "txt",
      filetype = "txt",
      commands = {
        rg = { flags = { "--type", "txt" } },
        git_grep = { globs = { "*.txt" } },
      },
    },
    typescript = {
      label = "typescript",
      filetype = "typescript",
      commands = {
        rg = { flags = { "--type", "typescript" } },
        git_grep = {
          globs = {
            "*.cts",
            "*.mts",
            "*.ts",
            "*.tsx",
          },
        },
      },
    },
    typoscript = {
      label = "typoscript",
      icon = { "", "DevIconTypeScript" },
      commands = {
        rg = { flags = { "--type", "typoscript" } },
        git_grep = {
          globs = {
            "*.ts",
            "*.typoscript",
          },
        },
      },
    },
    v = {
      label = "v",
      icon = { "󰍛", "DevIconVerilog" },
      commands = {
        rg = { flags = { "--type", "v" } },
        git_grep = {
          globs = {
            "*.v",
            "*.vsh",
          },
        },
      },
    },
    vala = {
      label = "vala",
      filetype = "vala",
      commands = {
        rg = { flags = { "--type", "vala" } },
        git_grep = { globs = { "*.vala" } },
      },
    },
    verilog = {
      label = "verilog",
      filetype = "verilog",
      commands = {
        rg = { flags = { "--type", "verilog" } },
        git_grep = {
          globs = {
            "*.sv",
            "*.svh",
            "*.v",
            "*.vh",
          },
        },
      },
    },
    vhdl = {
      label = "vhdl",
      filetype = "vhdl",
      commands = {
        rg = { flags = { "--type", "vhdl" } },
        git_grep = {
          globs = {
            "*.vhd",
            "*.vhdl",
          },
        },
      },
    },
    vim = {
      label = "vim",
      filetype = "vim",
      commands = {
        rg = { flags = { "--type", "vim" } },
        git_grep = {
          globs = {
            "*.vim",
            ".gvimrc",
            ".vimrc",
            "_gvimrc",
            "_vimrc",
            "gvimrc",
            "vimrc",
          },
        },
      },
    },
    vimscript = {
      label = "vimscript",
      icon = { "", "DevIconVim" },
      commands = {
        rg = { flags = { "--type", "vimscript" } },
        git_grep = {
          globs = {
            "*.vim",
            ".gvimrc",
            ".vimrc",
            "_gvimrc",
            "_vimrc",
            "gvimrc",
            "vimrc",
          },
        },
      },
    },
    vue = {
      label = "vue",
      filetype = "vue",
      commands = {
        rg = { flags = { "--type", "vue" } },
        git_grep = { globs = { "*.vue" } },
      },
    },
    xml = {
      label = "xml",
      filetype = "xml",
      commands = {
        rg = { flags = { "--type", "xml" } },
        git_grep = {
          globs = {
            "*.dtd",
            "*.rng",
            "*.sch",
            "*.xhtml",
            "*.xjb",
            "*.xml",
            "*.xml.dist",
            "*.xsd",
            "*.xsl",
            "*.xslt",
          },
        },
      },
    },
    xz = {
      label = "xz",
      icon = { "", "DevIconTxz" },
      commands = {
        rg = { flags = { "--type", "xz" } },
        git_grep = {
          globs = {
            "*.txz",
            "*.xz",
          },
        },
      },
    },
    yaml = {
      label = "yaml",
      filetype = "yaml",
      commands = {
        rg = { flags = { "--type", "yaml" } },
        git_grep = {
          globs = {
            "*.yaml",
            "*.yml",
          },
        },
      },
    },
    zig = {
      label = "zig",
      filetype = "zig",
      commands = {
        rg = { flags = { "--type", "zig" } },
        git_grep = { globs = { "*.zig" } },
      },
    },
    zsh = {
      label = "zsh",
      filetype = "zsh",
      commands = {
        rg = { flags = { "--type", "zsh" } },
        git_grep = {
          globs = {
            "*.zsh",
            ".zlogin",
            ".zlogout",
            ".zprofile",
            ".zshenv",
            ".zshrc",
            "zlogin",
            "zlogout",
            "zprofile",
            "zshenv",
            "zshrc",
          },
        },
      },
    },
    zstd = {
      label = "zstd",
      icon = { "", "DevIconZst" },
      commands = {
        rg = { flags = { "--type", "zstd" } },
        git_grep = {
          globs = {
            "*.zst",
            "*.zstd",
          },
        },
      },
    },
  },
}
