-- Auto-generated by the following command:
-- $ nvim --headless "+luafile generate_filetypes.lua" +q

---@type ContextGroup
return {
  title = "Filetypes",
  entries = {
    ada = {
      label = "ada",
      filetype = "ada",
      extension = "adb",
      commands = {
        rg = { flags = { "--type", "ada" } },
        git_grep = {
          globs = {
            "*.adb",
            "*.ads",
          },
        },
      },
    },
    aidl = {
      label = "aidl",
      filetype = "aidl",
      extension = "aidl",
      commands = {
        rg = { flags = { "--type", "aidl" } },
        git_grep = { globs = { "*.aidl" } },
      },
    },
    amake = {
      label = "amake",
      extension = "bp",
      commands = {
        rg = { flags = { "--type", "amake" } },
        git_grep = {
          globs = {
            "*.bp",
            "*.mk",
          },
        },
      },
    },
    asciidoc = {
      label = "asciidoc",
      filetype = "asciidoc",
      extension = "adoc",
      commands = {
        rg = { flags = { "--type", "asciidoc" } },
        git_grep = {
          globs = {
            "*.adoc",
            "*.asc",
            "*.asciidoc",
          },
        },
      },
    },
    asm = {
      label = "asm",
      filetype = "asm",
      extension = "S",
      commands = {
        rg = { flags = { "--type", "asm" } },
        git_grep = {
          globs = {
            "*.S",
            "*.asm",
            "*.s",
          },
        },
      },
    },
    asp = {
      label = "asp",
      extension = "asp",
      commands = {
        rg = { flags = { "--type", "asp" } },
        git_grep = {
          globs = {
            "*.ascx",
            "*.ascx.cs",
            "*.ascx.vb",
            "*.asp",
            "*.aspx",
            "*.aspx.cs",
            "*.aspx.vb",
          },
        },
      },
    },
    awk = {
      label = "awk",
      filetype = "awk",
      extension = "awk",
      commands = {
        rg = { flags = { "--type", "awk" } },
        git_grep = { globs = { "*.awk" } },
      },
    },
    bat = {
      label = "bat",
      filetype = "bat",
      extension = "bat",
      commands = {
        rg = { flags = { "--type", "bat" } },
        git_grep = { globs = { "*.bat" } },
      },
    },
    batch = {
      label = "batch",
      extension = "bat",
      commands = {
        rg = { flags = { "--type", "batch" } },
        git_grep = { globs = { "*.bat" } },
      },
    },
    bazel = {
      label = "bazel",
      extension = "bazel",
      commands = {
        rg = { flags = { "--type", "bazel" } },
        git_grep = {
          globs = {
            "*.BUILD",
            "*.bazel",
            "*.bazelrc",
            "*.bzl",
            "BUILD",
            "MODULE.bazel",
            "WORKSPACE",
            "WORKSPACE.bazel",
          },
        },
      },
    },
    bitbake = {
      label = "bitbake",
      filetype = "bitbake",
      extension = "bb",
      commands = {
        rg = { flags = { "--type", "bitbake" } },
        git_grep = {
          globs = {
            "*.bb",
            "*.bbappend",
            "*.bbclass",
            "*.conf",
            "*.inc",
          },
        },
      },
    },
    buildstream = {
      label = "buildstream",
      extension = "bst",
      commands = {
        rg = { flags = { "--type", "buildstream" } },
        git_grep = { globs = { "*.bst" } },
      },
    },
    bzip2 = {
      label = "bzip2",
      extension = "bz2",
      commands = {
        rg = { flags = { "--type", "bzip2" } },
        git_grep = {
          globs = {
            "*.bz2",
            "*.tbz2",
          },
        },
      },
    },
    c = {
      label = "c",
      filetype = "c",
      commands = {
        rg = { flags = { "--type", "c" } },
        git_grep = {
          globs = {
            "*.[chH]",
            "*.[chH].in",
            "*.cats",
          },
        },
      },
    },
    cabal = {
      label = "cabal",
      filetype = "cabal",
      extension = "cabal",
      commands = {
        rg = { flags = { "--type", "cabal" } },
        git_grep = { globs = { "*.cabal" } },
      },
    },
    clojure = {
      label = "clojure",
      filetype = "clojure",
      extension = "clj",
      commands = {
        rg = { flags = { "--type", "clojure" } },
        git_grep = {
          globs = {
            "*.clj",
            "*.cljc",
            "*.cljs",
            "*.cljx",
          },
        },
      },
    },
    cmake = {
      label = "cmake",
      filetype = "cmake",
      extension = "cmake",
      commands = {
        rg = { flags = { "--type", "cmake" } },
        git_grep = {
          globs = {
            "*.cmake",
            "CMakeLists.txt",
          },
        },
      },
    },
    cmd = {
      label = "cmd",
      extension = "bat",
      commands = {
        rg = { flags = { "--type", "cmd" } },
        git_grep = {
          globs = {
            "*.bat",
            "*.cmd",
          },
        },
      },
    },
    config = {
      label = "config",
      filetype = "config",
      extension = "cfg",
      commands = {
        rg = { flags = { "--type", "config" } },
        git_grep = {
          globs = {
            "*.cfg",
            "*.conf",
            "*.config",
            "*.ini",
          },
        },
      },
    },
    coq = {
      label = "coq",
      filetype = "coq",
      extension = "v",
      commands = {
        rg = { flags = { "--type", "coq" } },
        git_grep = { globs = { "*.v" } },
      },
    },
    cpp = {
      label = "cpp",
      filetype = "cpp",
      extension = "cc",
      commands = {
        rg = { flags = { "--type", "cpp" } },
        git_grep = {
          globs = {
            "*.[ChH]",
            "*.[ChH].in",
            "*.[ch]pp",
            "*.[ch]pp.in",
            "*.[ch]xx",
            "*.[ch]xx.in",
            "*.cc",
            "*.cc.in",
            "*.hh",
            "*.hh.in",
            "*.inl",
          },
        },
      },
    },
    crystal = {
      label = "crystal",
      filetype = "crystal",
      extension = "cr",
      commands = {
        rg = { flags = { "--type", "crystal" } },
        git_grep = {
          globs = {
            "*.cr",
            "*.ecr",
            "Projectfile",
            "shard.yml",
          },
        },
      },
    },
    csharp = {
      label = "csharp",
      filetype = "cs",
      extension = "cs",
      commands = {
        rg = { flags = { "--type", "csharp" } },
        git_grep = { globs = { "*.cs" } },
      },
    },
    cshtml = {
      label = "cshtml",
      extension = "cshtml",
      commands = {
        rg = { flags = { "--type", "cshtml" } },
        git_grep = { globs = { "*.cshtml" } },
      },
    },
    csproj = {
      label = "csproj",
      extension = "csproj",
      commands = {
        rg = { flags = { "--type", "csproj" } },
        git_grep = { globs = { "*.csproj" } },
      },
    },
    css = {
      label = "css",
      filetype = "css",
      extension = "css",
      commands = {
        rg = { flags = { "--type", "css" } },
        git_grep = {
          globs = {
            "*.css",
            "*.scss",
          },
        },
      },
    },
    csv = {
      label = "csv",
      filetype = "csv",
      extension = "csv",
      commands = {
        rg = { flags = { "--type", "csv" } },
        git_grep = { globs = { "*.csv" } },
      },
    },
    cuda = {
      label = "cuda",
      filetype = "cuda",
      extension = "cu",
      commands = {
        rg = { flags = { "--type", "cuda" } },
        git_grep = {
          globs = {
            "*.cu",
            "*.cuh",
          },
        },
      },
    },
    cython = {
      label = "cython",
      extension = "pxd",
      commands = {
        rg = { flags = { "--type", "cython" } },
        git_grep = {
          globs = {
            "*.pxd",
            "*.pxi",
            "*.pyx",
          },
        },
      },
    },
    d = {
      label = "d",
      filetype = "d",
      extension = "d",
      commands = {
        rg = { flags = { "--type", "d" } },
        git_grep = { globs = { "*.d" } },
      },
    },
    dart = {
      label = "dart",
      filetype = "dart",
      extension = "dart",
      commands = {
        rg = { flags = { "--type", "dart" } },
        git_grep = { globs = { "*.dart" } },
      },
    },
    devicetree = {
      label = "devicetree",
      extension = "dts",
      commands = {
        rg = { flags = { "--type", "devicetree" } },
        git_grep = {
          globs = {
            "*.dts",
            "*.dtsi",
          },
        },
      },
    },
    dhall = {
      label = "dhall",
      filetype = "dhall",
      extension = "dhall",
      commands = {
        rg = { flags = { "--type", "dhall" } },
        git_grep = { globs = { "*.dhall" } },
      },
    },
    diff = {
      label = "diff",
      filetype = "diff",
      extension = "diff",
      commands = {
        rg = { flags = { "--type", "diff" } },
        git_grep = {
          globs = {
            "*.diff",
            "*.patch",
          },
        },
      },
    },
    dockercompose = {
      label = "dockercompose",
      extension = "yml",
      commands = {
        rg = { flags = { "--type", "dockercompose" } },
        git_grep = {
          globs = {
            "docker-compose.*.yml",
            "docker-compose.yml",
          },
        },
      },
    },
    dts = {
      label = "dts",
      filetype = "dts",
      extension = "dts",
      commands = {
        rg = { flags = { "--type", "dts" } },
        git_grep = {
          globs = {
            "*.dts",
            "*.dtsi",
          },
        },
      },
    },
    ebuild = {
      label = "ebuild",
      extension = "ebuild",
      commands = {
        rg = { flags = { "--type", "ebuild" } },
        git_grep = {
          globs = {
            "*.ebuild",
            "*.eclass",
          },
        },
      },
    },
    edn = {
      label = "edn",
      extension = "edn",
      commands = {
        rg = { flags = { "--type", "edn" } },
        git_grep = { globs = { "*.edn" } },
      },
    },
    elisp = {
      label = "elisp",
      extension = "el",
      commands = {
        rg = { flags = { "--type", "elisp" } },
        git_grep = { globs = { "*.el" } },
      },
    },
    elixir = {
      label = "elixir",
      filetype = "elixir",
      extension = "eex",
      commands = {
        rg = { flags = { "--type", "elixir" } },
        git_grep = {
          globs = {
            "*.eex",
            "*.ex",
            "*.exs",
            "*.heex",
            "*.leex",
            "*.livemd",
          },
        },
      },
    },
    elm = {
      label = "elm",
      filetype = "elm",
      extension = "elm",
      commands = {
        rg = { flags = { "--type", "elm" } },
        git_grep = { globs = { "*.elm" } },
      },
    },
    erb = {
      label = "erb",
      extension = "erb",
      commands = {
        rg = { flags = { "--type", "erb" } },
        git_grep = { globs = { "*.erb" } },
      },
    },
    erlang = {
      label = "erlang",
      filetype = "erlang",
      extension = "erl",
      commands = {
        rg = { flags = { "--type", "erlang" } },
        git_grep = {
          globs = {
            "*.erl",
            "*.hrl",
          },
        },
      },
    },
    fennel = {
      label = "fennel",
      filetype = "fennel",
      extension = "fnl",
      commands = {
        rg = { flags = { "--type", "fennel" } },
        git_grep = { globs = { "*.fnl" } },
      },
    },
    fish = {
      label = "fish",
      filetype = "fish",
      extension = "fish",
      commands = {
        rg = { flags = { "--type", "fish" } },
        git_grep = { globs = { "*.fish" } },
      },
    },
    fortran = {
      label = "fortran",
      filetype = "fortran",
      extension = "F",
      commands = {
        rg = { flags = { "--type", "fortran" } },
        git_grep = {
          globs = {
            "*.F",
            "*.F77",
            "*.F90",
            "*.F95",
            "*.f",
            "*.f77",
            "*.f90",
            "*.f95",
            "*.pfo",
          },
        },
      },
    },
    fsharp = {
      label = "fsharp",
      filetype = "fsharp",
      extension = "fs",
      commands = {
        rg = { flags = { "--type", "fsharp" } },
        git_grep = {
          globs = {
            "*.fs",
            "*.fsi",
            "*.fsx",
          },
        },
      },
    },
    gap = {
      label = "gap",
      extension = "g",
      commands = {
        rg = { flags = { "--type", "gap" } },
        git_grep = {
          globs = {
            "*.g",
            "*.gap",
            "*.gd",
            "*.gi",
            "*.tst",
          },
        },
      },
    },
    gn = {
      label = "gn",
      filetype = "gn",
      extension = "gn",
      commands = {
        rg = { flags = { "--type", "gn" } },
        git_grep = {
          globs = {
            "*.gn",
            "*.gni",
          },
        },
      },
    },
    go = {
      label = "go",
      filetype = "go",
      extension = "go",
      commands = {
        rg = { flags = { "--type", "go" } },
        git_grep = { globs = { "*.go" } },
      },
    },
    gprbuild = {
      label = "gprbuild",
      extension = "gpr",
      commands = {
        rg = { flags = { "--type", "gprbuild" } },
        git_grep = { globs = { "*.gpr" } },
      },
    },
    gradle = {
      label = "gradle",
      extension = "gradle",
      commands = {
        rg = { flags = { "--type", "gradle" } },
        git_grep = {
          globs = {
            "*.gradle",
            "*.gradle.kts",
            "gradle-wrapper.*",
            "gradle.properties",
            "gradlew",
            "gradlew.bat",
          },
        },
      },
    },
    graphql = {
      label = "graphql",
      filetype = "graphql",
      extension = "graphql",
      commands = {
        rg = { flags = { "--type", "graphql" } },
        git_grep = {
          globs = {
            "*.graphql",
            "*.graphqls",
          },
        },
      },
    },
    groovy = {
      label = "groovy",
      filetype = "groovy",
      extension = "gradle",
      commands = {
        rg = { flags = { "--type", "groovy" } },
        git_grep = {
          globs = {
            "*.gradle",
            "*.groovy",
          },
        },
      },
    },
    gzip = {
      label = "gzip",
      extension = "gz",
      commands = {
        rg = { flags = { "--type", "gzip" } },
        git_grep = {
          globs = {
            "*.gz",
            "*.tgz",
          },
        },
      },
    },
    h = {
      label = "h",
      extension = "h",
      commands = {
        rg = { flags = { "--type", "h" } },
        git_grep = {
          globs = {
            "*.h",
            "*.hh",
            "*.hpp",
          },
        },
      },
    },
    haml = {
      label = "haml",
      filetype = "haml",
      extension = "haml",
      commands = {
        rg = { flags = { "--type", "haml" } },
        git_grep = { globs = { "*.haml" } },
      },
    },
    hare = {
      label = "hare",
      filetype = "hare",
      extension = "ha",
      commands = {
        rg = { flags = { "--type", "hare" } },
        git_grep = { globs = { "*.ha" } },
      },
    },
    haskell = {
      label = "haskell",
      filetype = "haskell",
      extension = "hs",
      commands = {
        rg = { flags = { "--type", "haskell" } },
        git_grep = {
          globs = {
            "*.c2hs",
            "*.cpphs",
            "*.hs",
            "*.hsc",
            "*.lhs",
          },
        },
      },
    },
    hbs = {
      label = "hbs",
      extension = "hbs",
      commands = {
        rg = { flags = { "--type", "hbs" } },
        git_grep = { globs = { "*.hbs" } },
      },
    },
    html = {
      label = "html",
      filetype = "html",
      extension = "htm",
      commands = {
        rg = { flags = { "--type", "html" } },
        git_grep = {
          globs = {
            "*.ejs",
            "*.htm",
            "*.html",
          },
        },
      },
    },
    janet = {
      label = "janet",
      filetype = "janet",
      extension = "janet",
      commands = {
        rg = { flags = { "--type", "janet" } },
        git_grep = { globs = { "*.janet" } },
      },
    },
    java = {
      label = "java",
      filetype = "java",
      extension = "java",
      commands = {
        rg = { flags = { "--type", "java" } },
        git_grep = {
          globs = {
            "*.java",
            "*.jsp",
            "*.jspx",
            "*.properties",
          },
        },
      },
    },
    jinja = {
      label = "jinja",
      filetype = "jinja",
      commands = {
        rg = { flags = { "--type", "jinja" } },
        git_grep = {
          globs = {
            "*.j2",
            "*.jinja",
            "*.jinja2",
          },
        },
      },
    },
    jl = {
      label = "jl",
      extension = "jl",
      commands = {
        rg = { flags = { "--type", "jl" } },
        git_grep = { globs = { "*.jl" } },
      },
    },
    js = {
      label = "js",
      extension = "cjs",
      commands = {
        rg = { flags = { "--type", "js" } },
        git_grep = {
          globs = {
            "*.cjs",
            "*.js",
            "*.jsx",
            "*.mjs",
            "*.vue",
          },
        },
      },
    },
    json = {
      label = "json",
      filetype = "json",
      extension = "json",
      commands = {
        rg = { flags = { "--type", "json" } },
        git_grep = {
          globs = {
            "*.json",
            "*.sarif",
            "composer.lock",
          },
        },
      },
    },
    jsonl = {
      label = "jsonl",
      filetype = "jsonl",
      extension = "jsonl",
      commands = {
        rg = { flags = { "--type", "jsonl" } },
        git_grep = { globs = { "*.jsonl" } },
      },
    },
    julia = {
      label = "julia",
      filetype = "julia",
      extension = "jl",
      commands = {
        rg = { flags = { "--type", "julia" } },
        git_grep = { globs = { "*.jl" } },
      },
    },
    jupyter = {
      label = "jupyter",
      extension = "ipynb",
      commands = {
        rg = { flags = { "--type", "jupyter" } },
        git_grep = {
          globs = {
            "*.ipynb",
            "*.jpynb",
          },
        },
      },
    },
    k = {
      label = "k",
      extension = "k",
      commands = {
        rg = { flags = { "--type", "k" } },
        git_grep = { globs = { "*.k" } },
      },
    },
    kotlin = {
      label = "kotlin",
      filetype = "kotlin",
      extension = "kt",
      commands = {
        rg = { flags = { "--type", "kotlin" } },
        git_grep = {
          globs = {
            "*.kt",
            "*.kts",
          },
        },
      },
    },
    lean = {
      label = "lean",
      filetype = "lean",
      extension = "lean",
      commands = {
        rg = { flags = { "--type", "lean" } },
        git_grep = { globs = { "*.lean" } },
      },
    },
    less = {
      label = "less",
      filetype = "less",
      extension = "less",
      commands = {
        rg = { flags = { "--type", "less" } },
        git_grep = { globs = { "*.less" } },
      },
    },
    lilypond = {
      label = "lilypond",
      filetype = "lilypond",
      extension = "ily",
      commands = {
        rg = { flags = { "--type", "lilypond" } },
        git_grep = {
          globs = {
            "*.ily",
            "*.ly",
          },
        },
      },
    },
    lisp = {
      label = "lisp",
      filetype = "lisp",
      extension = "el",
      commands = {
        rg = { flags = { "--type", "lisp" } },
        git_grep = {
          globs = {
            "*.el",
            "*.jl",
            "*.lisp",
            "*.lsp",
            "*.sc",
            "*.scm",
          },
        },
      },
    },
    lua = {
      label = "lua",
      filetype = "lua",
      extension = "lua",
      commands = {
        rg = { flags = { "--type", "lua" } },
        git_grep = { globs = { "*.lua" } },
      },
    },
    m4 = {
      label = "m4",
      filetype = "m4",
      extension = "m4",
      commands = {
        rg = { flags = { "--type", "m4" } },
        git_grep = {
          globs = {
            "*.ac",
            "*.m4",
          },
        },
      },
    },
    make = {
      label = "make",
      filetype = "make",
      extension = "mak",
      commands = {
        rg = { flags = { "--type", "make" } },
        git_grep = {
          globs = {
            "*.mak",
            "*.mk",
            "[Gg][Nn][Uu]makefile",
            "[Gg][Nn][Uu]makefile.am",
            "[Gg][Nn][Uu]makefile.in",
            "[Mm]akefile",
            "[Mm]akefile.am",
            "[Mm]akefile.in",
          },
        },
      },
    },
    man = {
      label = "man",
      filetype = "man",
      commands = {
        rg = { flags = { "--type", "man" } },
        git_grep = {
          globs = {
            "*.[0-9][cEFMmpSx]",
            "*.[0-9lnpx]",
          },
        },
      },
    },
    markdown = {
      label = "markdown",
      filetype = "markdown",
      extension = "markdown",
      commands = {
        rg = { flags = { "--type", "markdown" } },
        git_grep = {
          globs = {
            "*.markdown",
            "*.md",
            "*.mdown",
            "*.mdwn",
            "*.mdx",
            "*.mkd",
            "*.mkdn",
          },
        },
      },
    },
    matlab = {
      label = "matlab",
      filetype = "matlab",
      extension = "m",
      commands = {
        rg = { flags = { "--type", "matlab" } },
        git_grep = { globs = { "*.m" } },
      },
    },
    meson = {
      label = "meson",
      filetype = "meson",
      commands = {
        rg = { flags = { "--type", "meson" } },
        git_grep = {
          globs = {
            "meson.build",
            "meson.options",
            "meson_options.txt",
          },
        },
      },
    },
    ml = {
      label = "ml",
      extension = "ml",
      commands = {
        rg = { flags = { "--type", "ml" } },
        git_grep = { globs = { "*.ml" } },
      },
    },
    motoko = {
      label = "motoko",
      extension = "mo",
      commands = {
        rg = { flags = { "--type", "motoko" } },
        git_grep = { globs = { "*.mo" } },
      },
    },
    msbuild = {
      label = "msbuild",
      extension = "csproj",
      commands = {
        rg = { flags = { "--type", "msbuild" } },
        git_grep = {
          globs = {
            "*.csproj",
            "*.fsproj",
            "*.proj",
            "*.props",
            "*.sln",
            "*.targets",
            "*.vcxproj",
          },
        },
      },
    },
    nim = {
      label = "nim",
      filetype = "nim",
      extension = "nim",
      commands = {
        rg = { flags = { "--type", "nim" } },
        git_grep = {
          globs = {
            "*.nim",
            "*.nimble",
            "*.nimf",
            "*.nims",
          },
        },
      },
    },
    nix = {
      label = "nix",
      filetype = "nix",
      extension = "nix",
      commands = {
        rg = { flags = { "--type", "nix" } },
        git_grep = { globs = { "*.nix" } },
      },
    },
    objc = {
      label = "objc",
      filetype = "objc",
      extension = "h",
      commands = {
        rg = { flags = { "--type", "objc" } },
        git_grep = {
          globs = {
            "*.h",
            "*.m",
          },
        },
      },
    },
    objcpp = {
      label = "objcpp",
      filetype = "objcpp",
      extension = "h",
      commands = {
        rg = { flags = { "--type", "objcpp" } },
        git_grep = {
          globs = {
            "*.h",
            "*.mm",
          },
        },
      },
    },
    ocaml = {
      label = "ocaml",
      filetype = "ocaml",
      extension = "ml",
      commands = {
        rg = { flags = { "--type", "ocaml" } },
        git_grep = {
          globs = {
            "*.ml",
            "*.mli",
            "*.mll",
            "*.mly",
          },
        },
      },
    },
    org = {
      label = "org",
      filetype = "org",
      extension = "org",
      commands = {
        rg = { flags = { "--type", "org" } },
        git_grep = {
          globs = {
            "*.org",
            "*.org_archive",
          },
        },
      },
    },
    pascal = {
      label = "pascal",
      filetype = "pascal",
      extension = "dpr",
      commands = {
        rg = { flags = { "--type", "pascal" } },
        git_grep = {
          globs = {
            "*.dpr",
            "*.inc",
            "*.lpr",
            "*.pas",
            "*.pp",
          },
        },
      },
    },
    pdf = {
      label = "pdf",
      filetype = "pdf",
      extension = "pdf",
      commands = {
        rg = { flags = { "--type", "pdf" } },
        git_grep = { globs = { "*.pdf" } },
      },
    },
    perl = {
      label = "perl",
      filetype = "perl",
      extension = "PL",
      commands = {
        rg = { flags = { "--type", "perl" } },
        git_grep = {
          globs = {
            "*.PL",
            "*.perl",
            "*.pl",
            "*.plh",
            "*.plx",
            "*.pm",
            "*.t",
          },
        },
      },
    },
    php = {
      label = "php",
      filetype = "php",
      extension = "php",
      commands = {
        rg = { flags = { "--type", "php" } },
        git_grep = {
          globs = {
            "*.php",
            "*.php3",
            "*.php4",
            "*.php5",
            "*.php7",
            "*.php8",
            "*.pht",
            "*.phtml",
          },
        },
      },
    },
    po = {
      label = "po",
      filetype = "po",
      extension = "po",
      commands = {
        rg = { flags = { "--type", "po" } },
        git_grep = { globs = { "*.po" } },
      },
    },
    pod = {
      label = "pod",
      filetype = "pod",
      extension = "pod",
      commands = {
        rg = { flags = { "--type", "pod" } },
        git_grep = { globs = { "*.pod" } },
      },
    },
    postscript = {
      label = "postscript",
      extension = "eps",
      commands = {
        rg = { flags = { "--type", "postscript" } },
        git_grep = {
          globs = {
            "*.eps",
            "*.ps",
          },
        },
      },
    },
    prolog = {
      label = "prolog",
      filetype = "prolog",
      extension = "P",
      commands = {
        rg = { flags = { "--type", "prolog" } },
        git_grep = {
          globs = {
            "*.P",
            "*.pl",
            "*.pro",
            "*.prolog",
          },
        },
      },
    },
    protobuf = {
      label = "protobuf",
      extension = "proto",
      commands = {
        rg = { flags = { "--type", "protobuf" } },
        git_grep = { globs = { "*.proto" } },
      },
    },
    ps = {
      label = "ps",
      extension = "cdxml",
      commands = {
        rg = { flags = { "--type", "ps" } },
        git_grep = {
          globs = {
            "*.cdxml",
            "*.ps1",
            "*.ps1xml",
            "*.psd1",
            "*.psm1",
          },
        },
      },
    },
    puppet = {
      label = "puppet",
      filetype = "puppet",
      extension = "epp",
      commands = {
        rg = { flags = { "--type", "puppet" } },
        git_grep = {
          globs = {
            "*.epp",
            "*.erb",
            "*.pp",
            "*.rb",
          },
        },
      },
    },
    purs = {
      label = "purs",
      extension = "purs",
      commands = {
        rg = { flags = { "--type", "purs" } },
        git_grep = { globs = { "*.purs" } },
      },
    },
    python = {
      label = "python",
      filetype = "python",
      extension = "py",
      commands = {
        rg = { flags = { "--type", "python" } },
        git_grep = {
          globs = {
            "*.py",
            "*.pyi",
          },
        },
      },
    },
    qmake = {
      label = "qmake",
      extension = "pro",
      commands = {
        rg = { flags = { "--type", "qmake" } },
        git_grep = {
          globs = {
            "*.prf",
            "*.pri",
            "*.pro",
          },
        },
      },
    },
    qml = {
      label = "qml",
      filetype = "qml",
      extension = "qml",
      commands = {
        rg = { flags = { "--type", "qml" } },
        git_grep = { globs = { "*.qml" } },
      },
    },
    r = {
      label = "r",
      filetype = "r",
      extension = "R",
      commands = {
        rg = { flags = { "--type", "r" } },
        git_grep = {
          globs = {
            "*.R",
            "*.Rmd",
            "*.Rnw",
            "*.r",
          },
        },
      },
    },
    racket = {
      label = "racket",
      filetype = "racket",
      extension = "rkt",
      commands = {
        rg = { flags = { "--type", "racket" } },
        git_grep = { globs = { "*.rkt" } },
      },
    },
    raku = {
      label = "raku",
      filetype = "raku",
      extension = "p6",
      commands = {
        rg = { flags = { "--type", "raku" } },
        git_grep = {
          globs = {
            "*.p6",
            "*.pl6",
            "*.pm6",
            "*.raku",
            "*.rakudoc",
            "*.rakumod",
            "*.rakutest",
          },
        },
      },
    },
    red = {
      label = "red",
      extension = "r",
      commands = {
        rg = { flags = { "--type", "red" } },
        git_grep = {
          globs = {
            "*.r",
            "*.red",
            "*.reds",
          },
        },
      },
    },
    rescript = {
      label = "rescript",
      filetype = "rescript",
      extension = "res",
      commands = {
        rg = { flags = { "--type", "rescript" } },
        git_grep = {
          globs = {
            "*.res",
            "*.resi",
          },
        },
      },
    },
    robot = {
      label = "robot",
      filetype = "robot",
      extension = "robot",
      commands = {
        rg = { flags = { "--type", "robot" } },
        git_grep = { globs = { "*.robot" } },
      },
    },
    rst = {
      label = "rst",
      filetype = "rst",
      extension = "rst",
      commands = {
        rg = { flags = { "--type", "rst" } },
        git_grep = { globs = { "*.rst" } },
      },
    },
    ruby = {
      label = "ruby",
      filetype = "ruby",
      extension = "gemspec",
      commands = {
        rg = { flags = { "--type", "ruby" } },
        git_grep = {
          globs = {
            "*.gemspec",
            "*.rb",
            "*.rbw",
            ".irbrc",
            "Gemfile",
            "Rakefile",
            "config.ru",
          },
        },
      },
    },
    rust = {
      label = "rust",
      filetype = "rust",
      extension = "rs",
      commands = {
        rg = { flags = { "--type", "rust" } },
        git_grep = { globs = { "*.rs" } },
      },
    },
    sass = {
      label = "sass",
      filetype = "sass",
      extension = "sass",
      commands = {
        rg = { flags = { "--type", "sass" } },
        git_grep = {
          globs = {
            "*.sass",
            "*.scss",
          },
        },
      },
    },
    scala = {
      label = "scala",
      filetype = "scala",
      extension = "sbt",
      commands = {
        rg = { flags = { "--type", "scala" } },
        git_grep = {
          globs = {
            "*.sbt",
            "*.scala",
          },
        },
      },
    },
    sh = {
      label = "sh",
      filetype = "sh",
      extension = "bash",
      commands = {
        rg = { flags = { "--type", "sh" } },
        git_grep = {
          globs = {
            "*.bash",
            "*.bashrc",
            "*.csh",
            "*.cshrc",
            "*.ksh",
            "*.kshrc",
            "*.sh",
            "*.tcsh",
            "*.zsh",
            ".bash_login",
            ".bash_logout",
            ".bash_profile",
            ".bashrc",
            ".cshrc",
            ".kshrc",
            ".login",
            ".logout",
            ".profile",
            ".tcshrc",
            ".zlogin",
            ".zlogout",
            ".zprofile",
            ".zshenv",
            ".zshrc",
            "bash_login",
            "bash_logout",
            "bash_profile",
            "bashrc",
            "profile",
            "zlogin",
            "zlogout",
            "zprofile",
            "zshenv",
            "zshrc",
          },
        },
      },
    },
    smarty = {
      label = "smarty",
      filetype = "smarty",
      extension = "tpl",
      commands = {
        rg = { flags = { "--type", "smarty" } },
        git_grep = { globs = { "*.tpl" } },
      },
    },
    sml = {
      label = "sml",
      filetype = "sml",
      extension = "sml",
      commands = {
        rg = { flags = { "--type", "sml" } },
        git_grep = {
          globs = {
            "*.sig",
            "*.sml",
          },
        },
      },
    },
    solidity = {
      label = "solidity",
      filetype = "solidity",
      extension = "sol",
      commands = {
        rg = { flags = { "--type", "solidity" } },
        git_grep = { globs = { "*.sol" } },
      },
    },
    spec = {
      label = "spec",
      filetype = "spec",
      extension = "spec",
      commands = {
        rg = { flags = { "--type", "spec" } },
        git_grep = { globs = { "*.spec" } },
      },
    },
    sql = {
      label = "sql",
      filetype = "sql",
      extension = "sql",
      commands = {
        rg = { flags = { "--type", "sql" } },
        git_grep = {
          globs = {
            "*.psql",
            "*.sql",
          },
        },
      },
    },
    stylus = {
      label = "stylus",
      filetype = "stylus",
      extension = "styl",
      commands = {
        rg = { flags = { "--type", "stylus" } },
        git_grep = { globs = { "*.styl" } },
      },
    },
    sv = {
      label = "sv",
      extension = "h",
      commands = {
        rg = { flags = { "--type", "sv" } },
        git_grep = {
          globs = {
            "*.h",
            "*.sv",
            "*.svh",
            "*.v",
            "*.vg",
          },
        },
      },
    },
    svelte = {
      label = "svelte",
      filetype = "svelte",
      extension = "svelte",
      commands = {
        rg = { flags = { "--type", "svelte" } },
        git_grep = { globs = { "*.svelte" } },
      },
    },
    svg = {
      label = "svg",
      filetype = "svg",
      extension = "svg",
      commands = {
        rg = { flags = { "--type", "svg" } },
        git_grep = { globs = { "*.svg" } },
      },
    },
    swift = {
      label = "swift",
      filetype = "swift",
      extension = "swift",
      commands = {
        rg = { flags = { "--type", "swift" } },
        git_grep = { globs = { "*.swift" } },
      },
    },
    swig = {
      label = "swig",
      filetype = "swig",
      extension = "def",
      commands = {
        rg = { flags = { "--type", "swig" } },
        git_grep = {
          globs = {
            "*.def",
            "*.i",
          },
        },
      },
    },
    systemd = {
      label = "systemd",
      filetype = "systemd",
      commands = {
        rg = { flags = { "--type", "systemd" } },
        git_grep = {
          globs = {
            "*.automount",
            "*.conf",
            "*.device",
            "*.link",
            "*.mount",
            "*.path",
            "*.scope",
            "*.service",
            "*.slice",
            "*.socket",
            "*.swap",
            "*.target",
            "*.timer",
          },
        },
      },
    },
    tcl = {
      label = "tcl",
      filetype = "tcl",
      extension = "tcl",
      commands = {
        rg = { flags = { "--type", "tcl" } },
        git_grep = { globs = { "*.tcl" } },
      },
    },
    tex = {
      label = "tex",
      filetype = "tex",
      extension = "bib",
      commands = {
        rg = { flags = { "--type", "tex" } },
        git_grep = {
          globs = {
            "*.bib",
            "*.cls",
            "*.dtx",
            "*.ins",
            "*.ltx",
            "*.sty",
            "*.tex",
          },
        },
      },
    },
    texinfo = {
      label = "texinfo",
      filetype = "texinfo",
      extension = "texi",
      commands = {
        rg = { flags = { "--type", "texinfo" } },
        git_grep = { globs = { "*.texi" } },
      },
    },
    tf = {
      label = "tf",
      filetype = "tf",
      extension = "tf",
      commands = {
        rg = { flags = { "--type", "tf" } },
        git_grep = {
          globs = {
            "*.auto.tfvars",
            "*.auto.tfvars.json",
            "*.terraform.lock.hcl",
            "*.terraformrc",
            "*.tf",
            "*.tf.json",
            "*.tfrc",
            "terraform.rc",
            "terraform.tfvars",
            "terraform.tfvars.json",
          },
        },
      },
    },
    thrift = {
      label = "thrift",
      filetype = "thrift",
      extension = "thrift",
      commands = {
        rg = { flags = { "--type", "thrift" } },
        git_grep = { globs = { "*.thrift" } },
      },
    },
    toml = {
      label = "toml",
      filetype = "toml",
      extension = "toml",
      commands = {
        rg = { flags = { "--type", "toml" } },
        git_grep = {
          globs = {
            "*.toml",
            "Cargo.lock",
          },
        },
      },
    },
    twig = {
      label = "twig",
      filetype = "twig",
      extension = "twig",
      commands = {
        rg = { flags = { "--type", "twig" } },
        git_grep = { globs = { "*.twig" } },
      },
    },
    txt = {
      label = "txt",
      extension = "txt",
      commands = {
        rg = { flags = { "--type", "txt" } },
        git_grep = { globs = { "*.txt" } },
      },
    },
    typescript = {
      label = "typescript",
      filetype = "typescript",
      extension = "cts",
      commands = {
        rg = { flags = { "--type", "typescript" } },
        git_grep = {
          globs = {
            "*.cts",
            "*.mts",
            "*.ts",
            "*.tsx",
          },
        },
      },
    },
    typoscript = {
      label = "typoscript",
      extension = "ts",
      commands = {
        rg = { flags = { "--type", "typoscript" } },
        git_grep = {
          globs = {
            "*.ts",
            "*.typoscript",
          },
        },
      },
    },
    usd = {
      label = "usd",
      filetype = "usd",
      extension = "usd",
      commands = {
        rg = { flags = { "--type", "usd" } },
        git_grep = {
          globs = {
            "*.usd",
            "*.usda",
            "*.usdc",
          },
        },
      },
    },
    v = {
      label = "v",
      filetype = "v",
      extension = "v",
      commands = {
        rg = { flags = { "--type", "v" } },
        git_grep = {
          globs = {
            "*.v",
            "*.vsh",
          },
        },
      },
    },
    vala = {
      label = "vala",
      filetype = "vala",
      extension = "vala",
      commands = {
        rg = { flags = { "--type", "vala" } },
        git_grep = { globs = { "*.vala" } },
      },
    },
    vb = {
      label = "vb",
      filetype = "vb",
      extension = "vb",
      commands = {
        rg = { flags = { "--type", "vb" } },
        git_grep = { globs = { "*.vb" } },
      },
    },
    verilog = {
      label = "verilog",
      filetype = "verilog",
      extension = "sv",
      commands = {
        rg = { flags = { "--type", "verilog" } },
        git_grep = {
          globs = {
            "*.sv",
            "*.svh",
            "*.v",
            "*.vh",
          },
        },
      },
    },
    vhdl = {
      label = "vhdl",
      filetype = "vhdl",
      extension = "vhd",
      commands = {
        rg = { flags = { "--type", "vhdl" } },
        git_grep = {
          globs = {
            "*.vhd",
            "*.vhdl",
          },
        },
      },
    },
    vim = {
      label = "vim",
      filetype = "vim",
      extension = "vim",
      commands = {
        rg = { flags = { "--type", "vim" } },
        git_grep = {
          globs = {
            "*.vim",
            ".gvimrc",
            ".vimrc",
            "_gvimrc",
            "_vimrc",
            "gvimrc",
            "vimrc",
          },
        },
      },
    },
    vimscript = {
      label = "vimscript",
      extension = "vim",
      commands = {
        rg = { flags = { "--type", "vimscript" } },
        git_grep = {
          globs = {
            "*.vim",
            ".gvimrc",
            ".vimrc",
            "_gvimrc",
            "_vimrc",
            "gvimrc",
            "vimrc",
          },
        },
      },
    },
    vue = {
      label = "vue",
      filetype = "vue",
      extension = "vue",
      commands = {
        rg = { flags = { "--type", "vue" } },
        git_grep = { globs = { "*.vue" } },
      },
    },
    webidl = {
      label = "webidl",
      extension = "idl",
      commands = {
        rg = { flags = { "--type", "webidl" } },
        git_grep = {
          globs = {
            "*.idl",
            "*.webidl",
            "*.widl",
          },
        },
      },
    },
    wgsl = {
      label = "wgsl",
      filetype = "wgsl",
      extension = "wgsl",
      commands = {
        rg = { flags = { "--type", "wgsl" } },
        git_grep = { globs = { "*.wgsl" } },
      },
    },
    xml = {
      label = "xml",
      filetype = "xml",
      extension = "dtd",
      commands = {
        rg = { flags = { "--type", "xml" } },
        git_grep = {
          globs = {
            "*.dtd",
            "*.rng",
            "*.sch",
            "*.xhtml",
            "*.xjb",
            "*.xml",
            "*.xml.dist",
            "*.xsd",
            "*.xsl",
            "*.xslt",
          },
        },
      },
    },
    xz = {
      label = "xz",
      extension = "txz",
      commands = {
        rg = { flags = { "--type", "xz" } },
        git_grep = {
          globs = {
            "*.txz",
            "*.xz",
          },
        },
      },
    },
    yacc = {
      label = "yacc",
      filetype = "yacc",
      extension = "y",
      commands = {
        rg = { flags = { "--type", "yacc" } },
        git_grep = { globs = { "*.y" } },
      },
    },
    yaml = {
      label = "yaml",
      filetype = "yaml",
      extension = "yaml",
      commands = {
        rg = { flags = { "--type", "yaml" } },
        git_grep = {
          globs = {
            "*.yaml",
            "*.yml",
          },
        },
      },
    },
    yang = {
      label = "yang",
      filetype = "yang",
      extension = "yang",
      commands = {
        rg = { flags = { "--type", "yang" } },
        git_grep = { globs = { "*.yang" } },
      },
    },
    z = {
      label = "z",
      extension = "Z",
      commands = {
        rg = { flags = { "--type", "z" } },
        git_grep = { globs = { "*.Z" } },
      },
    },
    zig = {
      label = "zig",
      filetype = "zig",
      extension = "zig",
      commands = {
        rg = { flags = { "--type", "zig" } },
        git_grep = { globs = { "*.zig" } },
      },
    },
    zsh = {
      label = "zsh",
      filetype = "zsh",
      extension = "zsh",
      commands = {
        rg = { flags = { "--type", "zsh" } },
        git_grep = {
          globs = {
            "*.zsh",
            ".zlogin",
            ".zlogout",
            ".zprofile",
            ".zshenv",
            ".zshrc",
            "zlogin",
            "zlogout",
            "zprofile",
            "zshenv",
            "zshrc",
          },
        },
      },
    },
    zstd = {
      label = "zstd",
      extension = "zst",
      commands = {
        rg = { flags = { "--type", "zstd" } },
        git_grep = {
          globs = {
            "*.zst",
            "*.zstd",
          },
        },
      },
    },
  },
}
