-- Auto-generated by the following command:
-- $ nvim --headless "+luafile generate_filetypes.lua" +q

---@type ContextGroup
return {
  title = "Filetypes",
  entries = {
    ada = {
      label = "ada",
      filetype = "ada",
      commands = {
        rg = { flags = { "--type", "ada" } },
        git_grep = {
          globs = {
            "*.adb",
            "*.ads",
          },
        },
      },
    },
    aidl = {
      label = "aidl",
      filetype = "aidl",
      commands = {
        rg = { flags = { "--type", "aidl" } },
        git_grep = { globs = { "*.aidl" } },
      },
    },
    asciidoc = {
      label = "asciidoc",
      filetype = "asciidoc",
      commands = {
        rg = { flags = { "--type", "asciidoc" } },
        git_grep = {
          globs = {
            "*.adoc",
            "*.asc",
            "*.asciidoc",
          },
        },
      },
    },
    asm = {
      label = "asm",
      filetype = "asm",
      commands = {
        rg = { flags = { "--type", "asm" } },
        git_grep = {
          globs = {
            "*.S",
            "*.asm",
            "*.s",
          },
        },
      },
    },
    awk = {
      label = "awk",
      filetype = "awk",
      commands = {
        rg = { flags = { "--type", "awk" } },
        git_grep = { globs = { "*.awk" } },
      },
    },
    bat = {
      label = "bat",
      filetype = "bat",
      commands = {
        rg = { flags = { "--type", "bat" } },
        git_grep = { globs = { "*.bat" } },
      },
    },
    bitbake = {
      label = "bitbake",
      filetype = "bitbake",
      commands = {
        rg = { flags = { "--type", "bitbake" } },
        git_grep = {
          globs = {
            "*.bb",
            "*.bbappend",
            "*.bbclass",
            "*.conf",
            "*.inc",
          },
        },
      },
    },
    c = {
      label = "c",
      filetype = "c",
      commands = {
        rg = { flags = { "--type", "c" } },
        git_grep = {
          globs = {
            "*.[chH]",
            "*.[chH].in",
            "*.cats",
          },
        },
      },
    },
    cabal = {
      label = "cabal",
      filetype = "cabal",
      commands = {
        rg = { flags = { "--type", "cabal" } },
        git_grep = { globs = { "*.cabal" } },
      },
    },
    clojure = {
      label = "clojure",
      filetype = "clojure",
      commands = {
        rg = { flags = { "--type", "clojure" } },
        git_grep = {
          globs = {
            "*.clj",
            "*.cljc",
            "*.cljs",
            "*.cljx",
          },
        },
      },
    },
    cmake = {
      label = "cmake",
      filetype = "cmake",
      commands = {
        rg = { flags = { "--type", "cmake" } },
        git_grep = {
          globs = {
            "*.cmake",
            "CMakeLists.txt",
          },
        },
      },
    },
    config = {
      label = "config",
      filetype = "config",
      commands = {
        rg = { flags = { "--type", "config" } },
        git_grep = {
          globs = {
            "*.cfg",
            "*.conf",
            "*.config",
            "*.ini",
          },
        },
      },
    },
    coq = {
      label = "coq",
      filetype = "coq",
      commands = {
        rg = { flags = { "--type", "coq" } },
        git_grep = { globs = { "*.v" } },
      },
    },
    cpp = {
      label = "cpp",
      filetype = "cpp",
      commands = {
        rg = { flags = { "--type", "cpp" } },
        git_grep = {
          globs = {
            "*.[ChH]",
            "*.[ChH].in",
            "*.[ch]pp",
            "*.[ch]pp.in",
            "*.[ch]xx",
            "*.[ch]xx.in",
            "*.cc",
            "*.cc.in",
            "*.hh",
            "*.hh.in",
            "*.inl",
          },
        },
      },
    },
    crystal = {
      label = "crystal",
      filetype = "crystal",
      commands = {
        rg = { flags = { "--type", "crystal" } },
        git_grep = {
          globs = {
            "*.cr",
            "*.ecr",
            "Projectfile",
            "shard.yml",
          },
        },
      },
    },
    cs = {
      label = "cs",
      filetype = "cs",
      commands = {
        rg = { flags = { "--type", "cs" } },
        git_grep = { globs = { "*.cs" } },
      },
    },
    css = {
      label = "css",
      filetype = "css",
      commands = {
        rg = { flags = { "--type", "css" } },
        git_grep = {
          globs = {
            "*.css",
            "*.scss",
          },
        },
      },
    },
    csv = {
      label = "csv",
      filetype = "csv",
      commands = {
        rg = { flags = { "--type", "csv" } },
        git_grep = { globs = { "*.csv" } },
      },
    },
    cuda = {
      label = "cuda",
      filetype = "cuda",
      commands = {
        rg = { flags = { "--type", "cuda" } },
        git_grep = {
          globs = {
            "*.cu",
            "*.cuh",
          },
        },
      },
    },
    d = {
      label = "d",
      filetype = "d",
      commands = {
        rg = { flags = { "--type", "d" } },
        git_grep = { globs = { "*.d" } },
      },
    },
    dart = {
      label = "dart",
      filetype = "dart",
      commands = {
        rg = { flags = { "--type", "dart" } },
        git_grep = { globs = { "*.dart" } },
      },
    },
    dhall = {
      label = "dhall",
      filetype = "dhall",
      commands = {
        rg = { flags = { "--type", "dhall" } },
        git_grep = { globs = { "*.dhall" } },
      },
    },
    diff = {
      label = "diff",
      filetype = "diff",
      commands = {
        rg = { flags = { "--type", "diff" } },
        git_grep = {
          globs = {
            "*.diff",
            "*.patch",
          },
        },
      },
    },
    dts = {
      label = "dts",
      filetype = "dts",
      commands = {
        rg = { flags = { "--type", "dts" } },
        git_grep = {
          globs = {
            "*.dts",
            "*.dtsi",
          },
        },
      },
    },
    elixir = {
      label = "elixir",
      filetype = "elixir",
      commands = {
        rg = { flags = { "--type", "elixir" } },
        git_grep = {
          globs = {
            "*.eex",
            "*.ex",
            "*.exs",
            "*.heex",
            "*.leex",
            "*.livemd",
          },
        },
      },
    },
    elm = {
      label = "elm",
      filetype = "elm",
      commands = {
        rg = { flags = { "--type", "elm" } },
        git_grep = { globs = { "*.elm" } },
      },
    },
    erlang = {
      label = "erlang",
      filetype = "erlang",
      commands = {
        rg = { flags = { "--type", "erlang" } },
        git_grep = {
          globs = {
            "*.erl",
            "*.hrl",
          },
        },
      },
    },
    fennel = {
      label = "fennel",
      filetype = "fennel",
      commands = {
        rg = { flags = { "--type", "fennel" } },
        git_grep = { globs = { "*.fnl" } },
      },
    },
    fish = {
      label = "fish",
      filetype = "fish",
      commands = {
        rg = { flags = { "--type", "fish" } },
        git_grep = { globs = { "*.fish" } },
      },
    },
    fortran = {
      label = "fortran",
      filetype = "fortran",
      commands = {
        rg = { flags = { "--type", "fortran" } },
        git_grep = {
          globs = {
            "*.F",
            "*.F77",
            "*.F90",
            "*.F95",
            "*.f",
            "*.f77",
            "*.f90",
            "*.f95",
            "*.pfo",
          },
        },
      },
    },
    fsharp = {
      label = "fsharp",
      filetype = "fsharp",
      commands = {
        rg = { flags = { "--type", "fsharp" } },
        git_grep = {
          globs = {
            "*.fs",
            "*.fsi",
            "*.fsx",
          },
        },
      },
    },
    gn = {
      label = "gn",
      filetype = "gn",
      commands = {
        rg = { flags = { "--type", "gn" } },
        git_grep = {
          globs = {
            "*.gn",
            "*.gni",
          },
        },
      },
    },
    go = {
      label = "go",
      filetype = "go",
      commands = {
        rg = { flags = { "--type", "go" } },
        git_grep = { globs = { "*.go" } },
      },
    },
    graphql = {
      label = "graphql",
      filetype = "graphql",
      commands = {
        rg = { flags = { "--type", "graphql" } },
        git_grep = {
          globs = {
            "*.graphql",
            "*.graphqls",
          },
        },
      },
    },
    groovy = {
      label = "groovy",
      filetype = "groovy",
      commands = {
        rg = { flags = { "--type", "groovy" } },
        git_grep = {
          globs = {
            "*.gradle",
            "*.groovy",
          },
        },
      },
    },
    haml = {
      label = "haml",
      filetype = "haml",
      commands = {
        rg = { flags = { "--type", "haml" } },
        git_grep = { globs = { "*.haml" } },
      },
    },
    hare = {
      label = "hare",
      filetype = "hare",
      commands = {
        rg = { flags = { "--type", "hare" } },
        git_grep = { globs = { "*.ha" } },
      },
    },
    haskell = {
      label = "haskell",
      filetype = "haskell",
      commands = {
        rg = { flags = { "--type", "haskell" } },
        git_grep = {
          globs = {
            "*.c2hs",
            "*.cpphs",
            "*.hs",
            "*.hsc",
            "*.lhs",
          },
        },
      },
    },
    html = {
      label = "html",
      filetype = "html",
      commands = {
        rg = { flags = { "--type", "html" } },
        git_grep = {
          globs = {
            "*.ejs",
            "*.htm",
            "*.html",
          },
        },
      },
    },
    janet = {
      label = "janet",
      filetype = "janet",
      commands = {
        rg = { flags = { "--type", "janet" } },
        git_grep = { globs = { "*.janet" } },
      },
    },
    java = {
      label = "java",
      filetype = "java",
      commands = {
        rg = { flags = { "--type", "java" } },
        git_grep = {
          globs = {
            "*.java",
            "*.jsp",
            "*.jspx",
            "*.properties",
          },
        },
      },
    },
    jinja = {
      label = "jinja",
      filetype = "jinja",
      commands = {
        rg = { flags = { "--type", "jinja" } },
        git_grep = {
          globs = {
            "*.j2",
            "*.jinja",
            "*.jinja2",
          },
        },
      },
    },
    json = {
      label = "json",
      filetype = "json",
      commands = {
        rg = { flags = { "--type", "json" } },
        git_grep = {
          globs = {
            "*.json",
            "*.sarif",
            "composer.lock",
          },
        },
      },
    },
    jsonl = {
      label = "jsonl",
      filetype = "jsonl",
      commands = {
        rg = { flags = { "--type", "jsonl" } },
        git_grep = { globs = { "*.jsonl" } },
      },
    },
    julia = {
      label = "julia",
      filetype = "julia",
      commands = {
        rg = { flags = { "--type", "julia" } },
        git_grep = { globs = { "*.jl" } },
      },
    },
    kotlin = {
      label = "kotlin",
      filetype = "kotlin",
      commands = {
        rg = { flags = { "--type", "kotlin" } },
        git_grep = {
          globs = {
            "*.kt",
            "*.kts",
          },
        },
      },
    },
    lean = {
      label = "lean",
      filetype = "lean",
      commands = {
        rg = { flags = { "--type", "lean" } },
        git_grep = { globs = { "*.lean" } },
      },
    },
    less = {
      label = "less",
      filetype = "less",
      commands = {
        rg = { flags = { "--type", "less" } },
        git_grep = { globs = { "*.less" } },
      },
    },
    lilypond = {
      label = "lilypond",
      filetype = "lilypond",
      commands = {
        rg = { flags = { "--type", "lilypond" } },
        git_grep = {
          globs = {
            "*.ily",
            "*.ly",
          },
        },
      },
    },
    lisp = {
      label = "lisp",
      filetype = "lisp",
      commands = {
        rg = { flags = { "--type", "lisp" } },
        git_grep = {
          globs = {
            "*.el",
            "*.jl",
            "*.lisp",
            "*.lsp",
            "*.sc",
            "*.scm",
          },
        },
      },
    },
    lua = {
      label = "lua",
      filetype = "lua",
      commands = {
        rg = { flags = { "--type", "lua" } },
        git_grep = { globs = { "*.lua" } },
      },
    },
    m4 = {
      label = "m4",
      filetype = "m4",
      commands = {
        rg = { flags = { "--type", "m4" } },
        git_grep = {
          globs = {
            "*.ac",
            "*.m4",
          },
        },
      },
    },
    make = {
      label = "make",
      filetype = "make",
      commands = {
        rg = { flags = { "--type", "make" } },
        git_grep = {
          globs = {
            "*.mak",
            "*.mk",
            "[Gg][Nn][Uu]makefile",
            "[Gg][Nn][Uu]makefile.am",
            "[Gg][Nn][Uu]makefile.in",
            "[Mm]akefile",
            "[Mm]akefile.am",
            "[Mm]akefile.in",
          },
        },
      },
    },
    man = {
      label = "man",
      filetype = "man",
      commands = {
        rg = { flags = { "--type", "man" } },
        git_grep = {
          globs = {
            "*.[0-9][cEFMmpSx]",
            "*.[0-9lnpx]",
          },
        },
      },
    },
    markdown = {
      label = "markdown",
      filetype = "markdown",
      commands = {
        rg = { flags = { "--type", "markdown" } },
        git_grep = {
          globs = {
            "*.markdown",
            "*.md",
            "*.mdown",
            "*.mdwn",
            "*.mdx",
            "*.mkd",
            "*.mkdn",
          },
        },
      },
    },
    matlab = {
      label = "matlab",
      filetype = "matlab",
      commands = {
        rg = { flags = { "--type", "matlab" } },
        git_grep = { globs = { "*.m" } },
      },
    },
    meson = {
      label = "meson",
      filetype = "meson",
      commands = {
        rg = { flags = { "--type", "meson" } },
        git_grep = {
          globs = {
            "meson.build",
            "meson.options",
            "meson_options.txt",
          },
        },
      },
    },
    nim = {
      label = "nim",
      filetype = "nim",
      commands = {
        rg = { flags = { "--type", "nim" } },
        git_grep = {
          globs = {
            "*.nim",
            "*.nimble",
            "*.nimf",
            "*.nims",
          },
        },
      },
    },
    nix = {
      label = "nix",
      filetype = "nix",
      commands = {
        rg = { flags = { "--type", "nix" } },
        git_grep = { globs = { "*.nix" } },
      },
    },
    objc = {
      label = "objc",
      filetype = "objc",
      commands = {
        rg = { flags = { "--type", "objc" } },
        git_grep = {
          globs = {
            "*.h",
            "*.m",
          },
        },
      },
    },
    objcpp = {
      label = "objcpp",
      filetype = "objcpp",
      commands = {
        rg = { flags = { "--type", "objcpp" } },
        git_grep = {
          globs = {
            "*.h",
            "*.mm",
          },
        },
      },
    },
    ocaml = {
      label = "ocaml",
      filetype = "ocaml",
      commands = {
        rg = { flags = { "--type", "ocaml" } },
        git_grep = {
          globs = {
            "*.ml",
            "*.mli",
            "*.mll",
            "*.mly",
          },
        },
      },
    },
    org = {
      label = "org",
      filetype = "org",
      commands = {
        rg = { flags = { "--type", "org" } },
        git_grep = {
          globs = {
            "*.org",
            "*.org_archive",
          },
        },
      },
    },
    pascal = {
      label = "pascal",
      filetype = "pascal",
      commands = {
        rg = { flags = { "--type", "pascal" } },
        git_grep = {
          globs = {
            "*.dpr",
            "*.inc",
            "*.lpr",
            "*.pas",
            "*.pp",
          },
        },
      },
    },
    pdf = {
      label = "pdf",
      filetype = "pdf",
      commands = {
        rg = { flags = { "--type", "pdf" } },
        git_grep = { globs = { "*.pdf" } },
      },
    },
    perl = {
      label = "perl",
      filetype = "perl",
      commands = {
        rg = { flags = { "--type", "perl" } },
        git_grep = {
          globs = {
            "*.PL",
            "*.perl",
            "*.pl",
            "*.plh",
            "*.plx",
            "*.pm",
            "*.t",
          },
        },
      },
    },
    php = {
      label = "php",
      filetype = "php",
      commands = {
        rg = { flags = { "--type", "php" } },
        git_grep = {
          globs = {
            "*.php",
            "*.php3",
            "*.php4",
            "*.php5",
            "*.php7",
            "*.php8",
            "*.pht",
            "*.phtml",
          },
        },
      },
    },
    po = {
      label = "po",
      filetype = "po",
      commands = {
        rg = { flags = { "--type", "po" } },
        git_grep = { globs = { "*.po" } },
      },
    },
    pod = {
      label = "pod",
      filetype = "pod",
      commands = {
        rg = { flags = { "--type", "pod" } },
        git_grep = { globs = { "*.pod" } },
      },
    },
    prolog = {
      label = "prolog",
      filetype = "prolog",
      commands = {
        rg = { flags = { "--type", "prolog" } },
        git_grep = {
          globs = {
            "*.P",
            "*.pl",
            "*.pro",
            "*.prolog",
          },
        },
      },
    },
    puppet = {
      label = "puppet",
      filetype = "puppet",
      commands = {
        rg = { flags = { "--type", "puppet" } },
        git_grep = {
          globs = {
            "*.epp",
            "*.erb",
            "*.pp",
            "*.rb",
          },
        },
      },
    },
    python = {
      label = "python",
      filetype = "python",
      commands = {
        rg = { flags = { "--type", "python" } },
        git_grep = {
          globs = {
            "*.py",
            "*.pyi",
          },
        },
      },
    },
    qml = {
      label = "qml",
      filetype = "qml",
      commands = {
        rg = { flags = { "--type", "qml" } },
        git_grep = { globs = { "*.qml" } },
      },
    },
    r = {
      label = "r",
      filetype = "r",
      commands = {
        rg = { flags = { "--type", "r" } },
        git_grep = {
          globs = {
            "*.R",
            "*.Rmd",
            "*.Rnw",
            "*.r",
          },
        },
      },
    },
    racket = {
      label = "racket",
      filetype = "racket",
      commands = {
        rg = { flags = { "--type", "racket" } },
        git_grep = { globs = { "*.rkt" } },
      },
    },
    raku = {
      label = "raku",
      filetype = "raku",
      commands = {
        rg = { flags = { "--type", "raku" } },
        git_grep = {
          globs = {
            "*.p6",
            "*.pl6",
            "*.pm6",
            "*.raku",
            "*.rakudoc",
            "*.rakumod",
            "*.rakutest",
          },
        },
      },
    },
    rescript = {
      label = "rescript",
      filetype = "rescript",
      commands = {
        rg = { flags = { "--type", "rescript" } },
        git_grep = {
          globs = {
            "*.res",
            "*.resi",
          },
        },
      },
    },
    robot = {
      label = "robot",
      filetype = "robot",
      commands = {
        rg = { flags = { "--type", "robot" } },
        git_grep = { globs = { "*.robot" } },
      },
    },
    rst = {
      label = "rst",
      filetype = "rst",
      commands = {
        rg = { flags = { "--type", "rst" } },
        git_grep = { globs = { "*.rst" } },
      },
    },
    ruby = {
      label = "ruby",
      filetype = "ruby",
      commands = {
        rg = { flags = { "--type", "ruby" } },
        git_grep = {
          globs = {
            "*.gemspec",
            "*.rb",
            "*.rbw",
            ".irbrc",
            "Gemfile",
            "Rakefile",
            "config.ru",
          },
        },
      },
    },
    rust = {
      label = "rust",
      filetype = "rust",
      commands = {
        rg = { flags = { "--type", "rust" } },
        git_grep = { globs = { "*.rs" } },
      },
    },
    sass = {
      label = "sass",
      filetype = "sass",
      commands = {
        rg = { flags = { "--type", "sass" } },
        git_grep = {
          globs = {
            "*.sass",
            "*.scss",
          },
        },
      },
    },
    scala = {
      label = "scala",
      filetype = "scala",
      commands = {
        rg = { flags = { "--type", "scala" } },
        git_grep = {
          globs = {
            "*.sbt",
            "*.scala",
          },
        },
      },
    },
    sh = {
      label = "sh",
      filetype = "sh",
      commands = {
        rg = { flags = { "--type", "sh" } },
        git_grep = {
          globs = {
            "*.bash",
            "*.bashrc",
            "*.csh",
            "*.cshrc",
            "*.ksh",
            "*.kshrc",
            "*.sh",
            "*.tcsh",
            "*.zsh",
            ".bash_login",
            ".bash_logout",
            ".bash_profile",
            ".bashrc",
            ".cshrc",
            ".kshrc",
            ".login",
            ".logout",
            ".profile",
            ".tcshrc",
            ".zlogin",
            ".zlogout",
            ".zprofile",
            ".zshenv",
            ".zshrc",
            "bash_login",
            "bash_logout",
            "bash_profile",
            "bashrc",
            "profile",
            "zlogin",
            "zlogout",
            "zprofile",
            "zshenv",
            "zshrc",
          },
        },
      },
    },
    smarty = {
      label = "smarty",
      filetype = "smarty",
      commands = {
        rg = { flags = { "--type", "smarty" } },
        git_grep = { globs = { "*.tpl" } },
      },
    },
    sml = {
      label = "sml",
      filetype = "sml",
      commands = {
        rg = { flags = { "--type", "sml" } },
        git_grep = {
          globs = {
            "*.sig",
            "*.sml",
          },
        },
      },
    },
    solidity = {
      label = "solidity",
      filetype = "solidity",
      commands = {
        rg = { flags = { "--type", "solidity" } },
        git_grep = { globs = { "*.sol" } },
      },
    },
    spec = {
      label = "spec",
      filetype = "spec",
      commands = {
        rg = { flags = { "--type", "spec" } },
        git_grep = { globs = { "*.spec" } },
      },
    },
    sql = {
      label = "sql",
      filetype = "sql",
      commands = {
        rg = { flags = { "--type", "sql" } },
        git_grep = {
          globs = {
            "*.psql",
            "*.sql",
          },
        },
      },
    },
    stylus = {
      label = "stylus",
      filetype = "stylus",
      commands = {
        rg = { flags = { "--type", "stylus" } },
        git_grep = { globs = { "*.styl" } },
      },
    },
    svelte = {
      label = "svelte",
      filetype = "svelte",
      commands = {
        rg = { flags = { "--type", "svelte" } },
        git_grep = { globs = { "*.svelte" } },
      },
    },
    svg = {
      label = "svg",
      filetype = "svg",
      commands = {
        rg = { flags = { "--type", "svg" } },
        git_grep = { globs = { "*.svg" } },
      },
    },
    swift = {
      label = "swift",
      filetype = "swift",
      commands = {
        rg = { flags = { "--type", "swift" } },
        git_grep = { globs = { "*.swift" } },
      },
    },
    swig = {
      label = "swig",
      filetype = "swig",
      commands = {
        rg = { flags = { "--type", "swig" } },
        git_grep = {
          globs = {
            "*.def",
            "*.i",
          },
        },
      },
    },
    systemd = {
      label = "systemd",
      filetype = "systemd",
      commands = {
        rg = { flags = { "--type", "systemd" } },
        git_grep = {
          globs = {
            "*.automount",
            "*.conf",
            "*.device",
            "*.link",
            "*.mount",
            "*.path",
            "*.scope",
            "*.service",
            "*.slice",
            "*.socket",
            "*.swap",
            "*.target",
            "*.timer",
          },
        },
      },
    },
    tcl = {
      label = "tcl",
      filetype = "tcl",
      commands = {
        rg = { flags = { "--type", "tcl" } },
        git_grep = { globs = { "*.tcl" } },
      },
    },
    tex = {
      label = "tex",
      filetype = "tex",
      commands = {
        rg = { flags = { "--type", "tex" } },
        git_grep = {
          globs = {
            "*.bib",
            "*.cls",
            "*.dtx",
            "*.ins",
            "*.ltx",
            "*.sty",
            "*.tex",
          },
        },
      },
    },
    texinfo = {
      label = "texinfo",
      filetype = "texinfo",
      commands = {
        rg = { flags = { "--type", "texinfo" } },
        git_grep = { globs = { "*.texi" } },
      },
    },
    tf = {
      label = "tf",
      filetype = "tf",
      commands = {
        rg = { flags = { "--type", "tf" } },
        git_grep = {
          globs = {
            "*.auto.tfvars",
            "*.auto.tfvars.json",
            "*.terraform.lock.hcl",
            "*.terraformrc",
            "*.tf",
            "*.tf.json",
            "*.tfrc",
            "terraform.rc",
            "terraform.tfvars",
            "terraform.tfvars.json",
          },
        },
      },
    },
    thrift = {
      label = "thrift",
      filetype = "thrift",
      commands = {
        rg = { flags = { "--type", "thrift" } },
        git_grep = { globs = { "*.thrift" } },
      },
    },
    toml = {
      label = "toml",
      filetype = "toml",
      commands = {
        rg = { flags = { "--type", "toml" } },
        git_grep = {
          globs = {
            "*.toml",
            "Cargo.lock",
          },
        },
      },
    },
    twig = {
      label = "twig",
      filetype = "twig",
      commands = {
        rg = { flags = { "--type", "twig" } },
        git_grep = { globs = { "*.twig" } },
      },
    },
    typescript = {
      label = "typescript",
      filetype = "typescript",
      commands = {
        rg = { flags = { "--type", "typescript" } },
        git_grep = {
          globs = {
            "*.cts",
            "*.mts",
            "*.ts",
            "*.tsx",
          },
        },
      },
    },
    usd = {
      label = "usd",
      filetype = "usd",
      commands = {
        rg = { flags = { "--type", "usd" } },
        git_grep = {
          globs = {
            "*.usd",
            "*.usda",
            "*.usdc",
          },
        },
      },
    },
    v = {
      label = "v",
      filetype = "v",
      commands = {
        rg = { flags = { "--type", "v" } },
        git_grep = {
          globs = {
            "*.v",
            "*.vsh",
          },
        },
      },
    },
    vala = {
      label = "vala",
      filetype = "vala",
      commands = {
        rg = { flags = { "--type", "vala" } },
        git_grep = { globs = { "*.vala" } },
      },
    },
    vb = {
      label = "vb",
      filetype = "vb",
      commands = {
        rg = { flags = { "--type", "vb" } },
        git_grep = { globs = { "*.vb" } },
      },
    },
    verilog = {
      label = "verilog",
      filetype = "verilog",
      commands = {
        rg = { flags = { "--type", "verilog" } },
        git_grep = {
          globs = {
            "*.sv",
            "*.svh",
            "*.v",
            "*.vh",
          },
        },
      },
    },
    vhdl = {
      label = "vhdl",
      filetype = "vhdl",
      commands = {
        rg = { flags = { "--type", "vhdl" } },
        git_grep = {
          globs = {
            "*.vhd",
            "*.vhdl",
          },
        },
      },
    },
    vim = {
      label = "vim",
      filetype = "vim",
      commands = {
        rg = { flags = { "--type", "vim" } },
        git_grep = {
          globs = {
            "*.vim",
            ".gvimrc",
            ".vimrc",
            "_gvimrc",
            "_vimrc",
            "gvimrc",
            "vimrc",
          },
        },
      },
    },
    vue = {
      label = "vue",
      filetype = "vue",
      commands = {
        rg = { flags = { "--type", "vue" } },
        git_grep = { globs = { "*.vue" } },
      },
    },
    wgsl = {
      label = "wgsl",
      filetype = "wgsl",
      commands = {
        rg = { flags = { "--type", "wgsl" } },
        git_grep = { globs = { "*.wgsl" } },
      },
    },
    xml = {
      label = "xml",
      filetype = "xml",
      commands = {
        rg = { flags = { "--type", "xml" } },
        git_grep = {
          globs = {
            "*.dtd",
            "*.rng",
            "*.sch",
            "*.xhtml",
            "*.xjb",
            "*.xml",
            "*.xml.dist",
            "*.xsd",
            "*.xsl",
            "*.xslt",
          },
        },
      },
    },
    yacc = {
      label = "yacc",
      filetype = "yacc",
      commands = {
        rg = { flags = { "--type", "yacc" } },
        git_grep = { globs = { "*.y" } },
      },
    },
    yaml = {
      label = "yaml",
      filetype = "yaml",
      commands = {
        rg = { flags = { "--type", "yaml" } },
        git_grep = {
          globs = {
            "*.yaml",
            "*.yml",
          },
        },
      },
    },
    yang = {
      label = "yang",
      filetype = "yang",
      commands = {
        rg = { flags = { "--type", "yang" } },
        git_grep = { globs = { "*.yang" } },
      },
    },
    zig = {
      label = "zig",
      filetype = "zig",
      commands = {
        rg = { flags = { "--type", "zig" } },
        git_grep = { globs = { "*.zig" } },
      },
    },
    zsh = {
      label = "zsh",
      filetype = "zsh",
      commands = {
        rg = { flags = { "--type", "zsh" } },
        git_grep = {
          globs = {
            "*.zsh",
            ".zlogin",
            ".zlogout",
            ".zprofile",
            ".zshenv",
            ".zshrc",
            "zlogin",
            "zlogout",
            "zprofile",
            "zshenv",
            "zshrc",
          },
        },
      },
    },
  },
}
