-- generate_filetypes.lua

---@return string
local function get_rg_types()
  local handle = io.popen("rg --type-list")
  if not handle then
    return ""
  end
  local output = handle:read("*a")
  handle:close()
  return output
end

---Extract simple extensions
local function extract_safe_extensions(extlist)
  local extensions = {}
  for ext in extlist:gmatch("%*%.([%w_]+)") do
    table.insert(extensions, ext)
  end
  return extensions
end

---@param output string
---@return ContextEntries
local function parse_rg_type_list(output)
  local result = {}
  for line in output:gmatch("[^\r\n]+") do
    local filetype, extlist = line:match("([^:]+):%s*(.+)")
    if filetype and extlist then
      local safe_exts = extract_safe_extensions(extlist)
      local icon, hl = require("nvim-web-devicons").get_icon_by_filetype(filetype)
      local valid_filetype = (icon and true) or false
      local icon, hl
      if not icon then
        for _, ext in ipairs(safe_exts) do
          icon, hl = require("nvim-web-devicons").get_icon(nil, ext)
          if icon then
            print("icon: " .. icon)
            break
          end
        end
      end

      if not icon then
        print("skip " .. filetype)
      else
        local entry = {
          label = filetype, -- use lowercase label
          filetype = valid_filetype and filetype,
          icon = not valid_filetype and { icon, hl },
          commands = {
            rg = { flags = { "--type", filetype } },
            git_grep = { globs = {} },
          },
        }
        for ext in extlist:gmatch("%S+") do
          ext = ext:gsub(",$", "") -- remove trailing comma
          table.insert(entry.commands.git_grep.globs, ext)
        end
        result[filetype] = entry
      end
    end
  end
  return result
end

---@param tbl ContextEntries
---@param filepath string
local function write_lua_table(tbl, filepath)
  local file, err = io.open(filepath, "w")
  if not file then
    io.stderr:write("Error opening file for writing: " .. tostring(err) .. "\n")
    os.exit(1)
  end

  file:write('-- Auto-generated by the following command:\n-- $ nvim --headless "+luafile generate_filetypes.lua" +q\n\n')
  file:write("---@type ContextGroup\n")
  file:write("return {\n")
  file:write('  title = "Filetypes",\n')
  file:write("  entries = {\n")

  -- sort keys for stable output
  local keys = {}
  for k in pairs(tbl) do
    table.insert(keys, k)
  end
  table.sort(keys)

  for _, name in ipairs(keys) do
    local entry = tbl[name]
    file:write(string.format("    %s = {\n", name))
    file:write(string.format('      label = "%s",\n', entry.label))
    if entry.icon then
      file:write(string.format('      icon = { "%s", "%s" },\n', entry.icon[1], entry.icon[2]))
    elseif entry.filetype then
      file:write(string.format('      filetype = "%s",\n', entry.filetype))
    end
    file:write("      commands = {\n")
    file:write(string.format('        rg = { flags = { "--type", "%s" } },\n', name))
    local globs = entry.commands.git_grep.globs or {}
    if #globs > 1 then
      file:write("        git_grep = {\n")
      file:write("          globs = {\n")
      for _, g in ipairs(entry.commands.git_grep.globs) do
        file:write(string.format('            "%s",\n', g))
      end
      file:write("          },\n")
      file:write("        },\n")
    elseif #globs == 1 then
      file:write(string.format('        git_grep = { globs = { "%s" } },\n', globs[1]))
    end
    file:write("      },\n")
    file:write("    },\n")
  end

  file:write("  },\n")
  file:write("}\n")
  file:close()
end

-- Main
local rg_output = get_rg_types()
local parsed = parse_rg_type_list(rg_output)
write_lua_table(parsed, "filetypes.lua")
print("filetypes.lua written with " .. tostring(#vim.tbl_keys(parsed)) .. " entries.\n")
